### ISSUE TITLE
Self report has 0 used space

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-cli#100]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 4.0.4
Core:       1.3.1
Protocol:   0.7.0
```

Replace the values below using the output from `node --version`.

```
v4.4.2
```

### Expected Behavior

Please describe the program's expected behavior.

I have ~90MB shards on my windows pc.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"type":"info","message":"telemetry report {\"storage\":{\"free\":2147483648,\"used\":0},\"bandwidth\":{\"upload\":4.59,\"download\":15.01},\"contact\":{\"protocol\":\"0.7.0\",\"address\":\"192.168.123.124\",\"port\":5000,\"nodeID\":\"a18f837b8bd051fe940b87050c906090bd368dea\",\"lastSeen\":1467005723527},\"payment\":\"\"}","timestamp":"2016-06-27T05:35:56.502Z"}
```

My linux system is working fine.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start storjshare-cli on a windows pc

**Comment by littleskunk** [comment]
I have no payment address in my configuration file. That is correct.

**Comment by littleskunk** [comment]
Updated to nodejs 4.4.6 and the same problem.

**Comment by infertux** [comment]
I have a similar problem. `storjshare` has been running for about 24 hours and `used` is still 8192. It went from 0 to 8192 during the first few minutes and has been static ever since:

`telemetry report {\"storage\":{\"free\":2147475456,\"used\":8192}`

```
$ du -sh .storjshare/
48K     .storjshare/

$ grep -A3 storage .storjshare/config.json 
  "storage": {
    "path": "/home/storj/.storjshare",
    "size": 2,
    "unit": "GB"
```

**Comment by CurreE** [comment]
Same thing happening to me.  Mine was stuck on 8192 for a day, and has now gone up to 16384 and gotten stuck there, despite having 388 MB of shards acquired today. 

{"type":"info","message":"telemetry report {\"storage\":{\"free\":5497558122496,\"used\":16384},\"bandwidth\":{\"upload\":0.3,\"download\":0.39},\"contact\":{\"protocol\":\"0.7.0\"...
