### ISSUE TITLE
OpenError: IO error: lock /mnt/SJCX/farmer.db/LOCK: No locks available

### ISSUE THREAD

**Issue by brizio1971** [Storj/storjshare-cli#101]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Storjshare: v4.0.4
Core:   v1.3.2
Protocol: v0.7.0
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

program running 

### Actual Behavior
 
As soon I run the pm2 command in order to start storjshare-cli I get a lot of this error:

```
storjshare-0 OpenError: IO error: lock /mnt/SJCX/farmer.db/LOCK: No locks available
storjshare-0     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/levelup.js:119:34
storjshare-0     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

**Comment by super3** [comment]
Corrected the formatting. Are you running more than one cli farmer?

**Comment by brizio1971** [comment]
No, my machine crashed, then I upgraded the cli version and restart as usual and I had the log full with this error.

**Comment by brizio1971** [comment]
I have try to clear the farmer.db folder and start from scratch but the error still remain, any ideas ? now my db is empty ....is something related to my SJCX address ?

**Comment by bookchin** [comment]
This exception will be thrown if two instances are trying to access the same LevelDB directory. If you wish to run multiple farmers, be sure to use the `--datadir` option to specify another location. If this is happening inadvertently, make sure there isn't a zombie process chilling out somewhere.
