### ISSUE TITLE
Improve configuration: add concurrency config wizard

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-cli#103]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 4.0.4
Core:       1.3.4
Protocol:   0.7.0
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Concurrency is a hidden configuration. A few user request it as part of the config wizard. I am not sure that is a good idea. They can easy run into timeouts and get no shards. See https://storj.readme.io/docs/storjshare-troubleshooting-guide#rpc-call-timed-out

```
 [...] > Enter the concurrent offer limit > (3)
```

A good compromise would be a warning. Any ideas?

**Comment by super3** [comment]
Just talked to @bookchin and he says it makes sense to add. I believe we are already adding this in the GUI.
