### ISSUE TITLE
Configuration tunnel connection 0 and concurrency 0 overwritten by default values

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-cli#104]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 4.0.4
Core:       1.3.4
Protocol:   0.7.0
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

Please describe the program's expected behavior.

Tunnel connection 0 = Don't allow any tunnel connection
Concurrency 0 = Don't send any offer. Needed for multiple nodes on the same machine. All nodes online but only one node is sending out offers to get more shards.

Use the default value if the configuration is missing.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Default value is used if the configuration is missing or the value is 0.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start node with tunnel connection 0, concurrency 0 and loglevel debug
2. First logline will print out the number of tunnel connections
3. First contract will show pending offers less than concurrency true / false

**Comment by bookchin** [comment]
#110 fixes concurrency override, but i think the tunnel connections issue is in core

**Comment by bookchin** [comment]
https://github.com/Storj/core/issues/247
