### ISSUE TITLE
JS stack trace

### ISSUE THREAD

**Issue by soeren-b-c** [Storj/storjshare-cli#114]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 4.0.4
Core:       1.3.6
Protocol:   0.7.0

```

Replace the values below using the output from `node --version`.

~$ node --version
v4.4.4

### Expected Behavior

Please describe the program's expected behavior.

### Actual Behavior

The gui freezes.
Terminal output below. I run storj from the .deb file

$ ./storjshare 

<--- Last few GCs --->

 4790566 ms: Mark-sweep 1094.2 (1418.7) -> 1088.7 (1418.7) MB, 105.0 / 20.0 ms [allocation failure] [GC in old space requested].
 4790663 ms: Mark-sweep 1088.7 (1418.7) -> 1088.7 (1418.7) MB, 96.2 / 16.1 ms [allocation failure] [GC in old space requested].
 4791138 ms: Mark-sweep 1088.7 (1418.7) -> 1100.6 (1403.7) MB, 473.8 / 377.1 ms [last resort gc].
 4791609 ms: Mark-sweep 1100.6 (1403.7) -> 1112.5 (1403.7) MB, 471.1 / 380.1 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3d2db7214a59 <String[7]: file://>
    1: get [/home/storj/storj-deb-install/opt/storjshare/resources/app.asar/node_modules/vue/dist/vue.common.js:~573] [pc=0xb99bd3f0014] (this=0x337254fc4e69 <a Cache with map 0xcc8e0470ba9>,key=0x28c6f3a04201 <Very long string[65463]>,returnEntry=0xc969ce04301 <undefined>)
    2: arguments adaptor frame: 1->2
    3: stringToFragment(aka stringToFragment) [/home/storj/storj-deb-install...

### Steps to Reproduce

Can't reproduce, but has happened 2-3 times.

**Comment by bookchin** [comment]
Do you mind reopening this in Storj/storjshare-gui? This repository is for the CLI.
