### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by fher98** [Storj/storjshare-cli#116]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 4.0.5
Core:       1.4.0
Protocol:   0.7.1

```

Replace the values below using the output from `node --version`.

```
v4.4.4

```

### Expected Behavior

It was working fine until friday, it crashed around 3am. An as soon as the cli is launched it crashes with a "bus error" message.

### Actual Behavior
storjshare start --datadir /.storjshare
 [...]  > Unlock your private key to start storj  >  *******************

{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-07-10T13:59:45.769Z"}
{"level":"info","message":"node created with nodeID a2561e7e959d6b4bfb30a53ace4502b80acaee41","timestamp":"2016-07-10T13:59:45.805Z"}
{"level":"info","message":"resolving seeds from https://api.storj.io","timestamp":"2016-07-10T13:59:45.805Z"}
{"level":"info","message":"attempting to join network via storj://24.37.48.14:38847/399051d44202d1e576bb0bcba78718e42a448634","timestamp":"2016-07-10T13:59:46.411Z"}
{"level":"debug","message":"entering overlay network via {\"protocol\":\"0.7.1\",\"address\":\"24.37.48.14\",\"port\":38847,\"nodeID\":\"399051d44202d1e576bb0bcba78718e42a448634\",\"lastSeen\":1468159186412}","timestamp":"2016-07-10T13:59:46.412Z"}
{"level":"debug","message":"updating contact {\"protocol\":\"0.7.1\",\"address\":\"24.37.48.14\",\"port\":38847,\"nodeID\":\"399051d44202d1e576bb0bcba78718e42a448634\",\"lastSeen\":1468159186412}","timestamp":"2016-07-10T13:59:46.414Z"}
{"level":"debug","message":"creating new bucket for contact at index 159","timestamp":"2016-07-10T13:59:46.414Z"}
{"level":"debug","message":"contact not in bucket, moving to head","timestamp":"2016-07-10T13:59:46.415Z"}
{"level":"debug","message":"searching for nodes close to key a2561e7e959d6b4bfb30a53ace4502b80acaee41","timestamp":"2016-07-10T13:59:46.416Z"}
{"level":"debug","message":"performing network walk for NODE a2561e7e959d6b4bfb30a53ace4502b80acaee41","timestamp":"2016-07-10T13:59:46.419Z"}
{"level":"debug","message":"starting contact iteration for key a2561e7e959d6b4bfb30a53ace4502b80acaee41","timestamp":"2016-07-10T13:59:46.419Z"}
{"level":"debug","message":"querying 399051d44202d1e576bb0bcba78718e42a448634 for key a2561e7e959d6b4bfb30a53ace4502b80acaee41","timestamp":"2016-07-10T13:59:46.420Z"}
{"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.7.1\",\"address\":\"24.37.48.14\",\"port\":38847,\"nodeID\":\"399051d44202d1e576bb0bcba78718e42a448634\",\"lastSeen\":1468159186421}","timestamp":"2016-07-10T13:59:46.421Z"}
Bus error

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... Please see the log, thanks.

**Comment by littleskunk** [comment]
Which OS are you running?

**Comment by fher98** [comment]
Hello, its a debian stretch, thanks. Was running fine, actually im  hosting 91GB from the network.

**Comment by littleskunk** [comment]
You can reproduce the crash? Is it always the firt FIND_NODE message? Is is crashing the same time or a few seconds later?

Are you sure you are running storjshare with node version v4.4.4?

**Comment by fher98** [comment]
Hi, well I always run the following before starting storj

:~$ nvm use 4.4.4
Now using node v4.4.4 (npm v2.15.1)
:~$ node --version
v4.4.4
Let me check de FIND_NODE

**Comment by fher98** [comment]
Ok, now its crashing different, tried it three times, with same output. Do you think I should erase the shards? 

 [...]  > Unlock your private key to start storj  >

{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-07-13T17:30:59.234Z"}
{"level":"info","message":"node created with nodeID a2561e7e959d6b4bfb30a53ace4502b80acaee41","timestamp":"2016-07-13T17:30:59.273Z"}
{"level":"info","message":"resolving seeds from https://api.storj.io","timestamp":"2016-07-13T17:30:59.274Z"}
Bus error

**Comment by super3** [comment]
@fher98 There has been a major release since you listed this issue. Can you verify that it still exists?

**Comment by fher98** [comment]
@super3 OK let me check. At the end I removed the farmer.db dir, so I lost the 91GB I was hosting. Restarted, no problem ther. Now Im hosting +150GB. Ill update then.

**Comment by fher98** [comment]
@super3 I updated on monday and for the last 48+ hours its been working without failure. I already doubled what I was hosting, just passed de 200GB mark. thanks
