### ISSUE TITLE
Min_free parameter request

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#117]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare:  4.0.5
Core:          1.4.0
Protocol:    0.7.1
```

Replace the values below using the output from `node --version`.

```
v6.2.2
```

### Expected Behavior

Utilize up to the specified quantity of disk space, but might an effort to maintain a minimum amount of free space based on a configurable parameter.

### Actual Behavior

Currently only the amount of space the node is allowed to use is configurable.  This leads to excessively complex implementation such as what I'm currently doing:  (8) nodes of 1TB each running on the same server so that I could disable one or more nodes should my free space be consumed by normal (non-storj related) files.

Note this feature was available in Test Group B CLI code.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by littleskunk** [comment]
Thank your for the good idea and thank your for the comment in https://github.com/Storj/storjshare-cli/issues/92.
