### ISSUE TITLE
Log wrapping

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#119]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare:  4.0.5
Core:          1.4.0
Protocol:     0.7.1
```

Replace the values below using the output from `node --version`.

```
v6.2.2
```

### Expected Behavior

Log files will wrap at a parameter driven size.

### Actual Behavior

Log files today are simply I/O redirected and grow continuously.  After 4 days, one node with debug set at Info level has generated over 2GB of log files.  Perhaps the last 10 or 100MB would contain the most useful information if there was a problem.

```
Believe I had already posted this enhancement request, but could not find it.  My apologize if this is a duplication - just found myself hung this morning trying to vi that log. 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. I/O redirect the console output to a log file.
2. Run for several days
3. ...

**Comment by bookchin** [comment]
I'm pretty adamant about not adding code to that is what I believe to be out of the scope of the application's purpose. It creates more overhead to manage and strays too far from the unix philosophy.

That said, I recognize the necessity for this feature. We use `logrotate` to manage this. See how we do this for bridge here: https://github.com/Storj/chef-storj/blob/master/recipes/bridge.rb

That chef recipe produces this logrotate configuration:

```
"/var/log/storj/bridge.log" {
  daily
  create 644 storj storj
  rotate 7
  missingok
  compress
  delaycompress
  copytruncate
  notifempty
}
```

**Comment by 1credit** [comment]
Thanks.  I'll give logrotate a shot.
