### ISSUE TITLE
Sotrj appears to be overloading modem

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#120]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: v4.0.5
Core:   v1.4.0
Protocol: 0.7.1
```

Replace the values below using the output from `node --version`.

```
v6.2.2
```

### Expected Behavior

Internet modem should be able to handle all traffic being thrown at it, including storj and the thousands of connections the bridges are currently holding open.

### Actual Behavior

General packet loss of between 7% and 50% across all paths to the modem.  Shutdown Storj, wait for connections to timeout, and packet loss drops to 0%.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by littleskunk** [comment]
Please try again with correct nodejs version.

**Comment by 1credit** [comment]
I'm running the latest node.js supported by my distribution - note its two major version OVER what storjshare requires (6.2.2 vs 4.4.4).
