### ISSUE TITLE
Linux tuning parameters

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#121]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: v2.2.4
Core:   v0.6.5
```

Replace the values below using the output from `node --version`.

```
v4.2.3
```

### Expected Behavior

Linux should handle everything out of the box.

### Actual Behavior

Most linux distributions are tuned for typical desktop applications.  Storj is not typical.  Recommend the following link be read:  http://www.nateware.com/linux-network-tuning-for-2013.html#.V4eT7aLAY-I

This MAY be related to the previously reported DDOS and packet dropping issue.  My linux server has been modified per the above link and monitoring is underway.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by littleskunk** [comment]
Old storjshare-cli version + old core version and old nodejs version. Don't forget to update everything. If you have any enhancement idea please create a new github issue.
