### ISSUE TITLE
Excessive DNS usage

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#125]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare:  5.0.0
Core:          2.0.0
Protocol:     0.7.1
```

Replace the values below using the output from `node --version`.

```
V4.4.6
```

### Expected Behavior

Node names specified in the config.json file would be resolved upon startup and IP addresses would be used message communication.

### Actual Behavior

While monitoring port usage on my Storj file server, I noticed an unusual amount of port 53 traffic (DNS).  This was significant enough that I added a DNS caching server to the environment, which, of course, resolved the problem.

Upon examining log files, it became apparent that nodenames, vs. node IPs, were being passed in messages.  This explained all the lookup activity.  Although such activity is not a big deal if a LAN based DNS server is being used, many people use 4.4.4.4 or 8.8.8.8 which would require IP traffic out to those public DNS servers for every message.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run the storjshare cli, establish a level 3 log file
2. View contents of log file and look for nodenames
3. ...

**Comment by 1credit** [comment]
After a bit of contemplation, I suspect just adding a recommendation for installation of a DNS caching server would be cleaner - although the code path is obviously a lot longer.  There are many, from the granddaddy Bind to nscd to unscd and others.

The main advantage of a caching server would be the handling of DDNS servers, along with the TTL logic each would honor.  

Mixed emotions on this.

**Comment by bookchin** [comment]
I don't see this getting implemented on the storj side anytime soon, but would happily accept a PR that adds some info to the README that outlines how to set this up with existing tools.
