### ISSUE TITLE
Problem updating Ubuntu with Storj installed

### ISSUE THREAD

**Issue by mariuspo** [Storj/storjshare-cli#126]
### Package Versions
Ubuntu 16.04
Storj Share : 0.9.1
Core Library:   v1.4.0
Protocol: 0.7.1

node --version not installed

### Expected Behavior
sudo apt-get upgrade working

### Actual Behavior
Errors were encountered while processing:
 storjshare
E: Sub-process /usr/bin/dpkg returned an error code (1)

### Steps to Reproduce
1. sudo apt-get update
2. sudo apt-get upgrade

**Comment by bookchin** [comment]
This actually looks like it belongs in the GUI repo: https://github.com/Storj/storjshare-gui/issues
