### ISSUE TITLE
Tunnels are opened even when disabled.

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#138]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare:  5.0.1
Core:          2.0.7
Protocol:    0.7.1
```

Replace the values below using the output from `node --version`.

```
v4.4.6
```

### Expected Behavior

Use of "tunnels": -1 in the config.json file should disabled all tunnel activity.

### Actual Behavior
It doesn't.  I noticed this while monitoring port usage:
http://puu.sh/qgIxD/e197b41b7e.png
Note the usage of port 4036 with 30 connections.  My config.json, attached below, utilizes port 4030 for the network, port 4031 for the tunnel server, and has ports 4032-4039 defined as tunnel ports.  However the # of Tunnels parameter is set to -1

Log snippet showing configuration setting and activity, full log in the attached zip file.

https://storjcommunity.slack.com/files/cassey/F1VR4CRTP/tunnel.log

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1.  Use my config.json file and launch a node
2.  Monitor port usage via netstat (recommend watch -n 2 netstat -nt | tail -n +3 | awk '{print $4}' | cut -d: -f2 | sort | uniq -c | sort -n -r
3.  Verify what you see by examining the logs
4.  Believe Cassey next time <lol>
[node3.zip](https://github.com/Storj/storjshare-cli/files/387315/node3.zip)

3. ...

**Comment by super3** [comment]
@1credit @littleskunk I believe this was fixed when #294 was merged.

**Comment by 1credit** [comment]
Is that Skunks core patch?

**Comment by utdrmac** [comment]
@super3 I don't believe this has been fixed. I have number of tunnels set to 0 yet the socket is open and listening:

```
root@drmac-ubuntu:~/.config/Storj Share# netstat -napt | grep 4102
tcp        0      0 0.0.0.0:4102            0.0.0.0:*               LISTEN      8452/storjshare --t
```

**Comment by bookchin** [comment]
the tunserver port will still open, but won't create any gateways for tunnels

**Comment by utdrmac** [comment]
Why open it if not going to use it?
