### ISSUE TITLE
ECDSA Key migration (nodeID) CLI <-> GUI

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-cli#139]
As farmer I would like to start farming with GUI / CLI and later switch to CLI / GUI without loosing my shards.

The GUI is storing the private key in the settings.json file:
`"key": "e12d20fbbcbf2e92e066613e146aa05bba0a2d77ba8451b6acf16a2758a3b828"`

The CLI is storig the key in id_ecdsa file. The key is crypted and a different format:
`2iSsJikC8STeGfkwK9GWcrx7FnNgakm8ezEQk7Hpg6WC7SPLCaBzpF7ZWgbmX4kd2R2RDNWiV5kfsabVxy5k4a91LJaJyHoU8ap89zAZ1UAzcx`

Feature request:
1.) Add a new key migration command for the CLI. Print out the CLI key in GUI format would allow me to copy the key into my GUI settings.json. 
2.) I would like to start the CLI setup and give it my GUI key.

https://github.com/Storj/core/blob/306834776680fcb5e9398ef0c331702261517385/lib/utils.js#L173-L201

**Comment by mo35** [comment]
on my wish list too , since now gui seems stable and performing well (not to mention its looks cool and have all info and config options needed) , i would gladly reduce amount of opened console windows by migrating to single gui

**Comment by br3nn** [comment]
I agree, I would like this feature, Going from CLI to the Nice clean looking GUI,

**Comment by bookchin** [comment]
Let's add a  `storjshare show-key` command to the CLI and a field to the GUI settings to paste in a custom key (and display the key in use).
