### ISSUE TITLE
All nodes returning missing or empty

### ISSUE THREAD

**Issue by utdrmac** [Storj/storjshare-cli#141]
I'm using the latest Windows GUI here but this isn't a "gui" issue. If it belongs elsewhere, I'll re-submit.

### Expected Behavior

- for drive shares to function
- be able to run more than 1 share

### Actual Behavior

- repeated attempts to contact multiple nodes results in failure. see attached log.

### Steps to Reproduce

My steps: stop storjshare.exe; remove config dir (C:/Users/drmac/AppData/Roaming/Storj Share/); start storj. add payout address. specify D:\storj10 and 10GB as share. set number of tunnels to 0. set external IP/hostname. click start. wait for connections to network that never finish.
[Drive-0_2016-7-29.log.gz](https://github.com/Storj/storjshare-cli/files/391408/Drive-0_2016-7-29.log.gz)

**Comment by littleskunk** [comment]
https://storj.readme.io/docs/storjshare-troubleshooting-guide#rpc-call-timed-out

```
With 100% timeouts you should check port forwarding, firewall, virus scanner and syncronize your clock with a good internet time server like time.nist.gov. 
```

**Comment by utdrmac** [comment]
@littleskunk Please re-open this. I am unable to run more than 1 node at a time, even on linux GUI. The 2nd node always returns 0/empty. I've noticed that UPNP/NAT only functions for 1 drive as indicated in the logs.

**Comment by littleskunk** [comment]
You read the troubleshooting guide in less than 4 minutes? That is awesome. Now take some more time and read it again.

If you would like to use UPnP please configurate a private IP because of this issue: https://github.com/Storj/core/issues/295#issuecomment-236394957

**Comment by utdrmac** [comment]
Port forwarding via UPnP is my only option. The advice, as you pasted above, is to check ports and enable forwarding. Not an option. I configured both drive shares to use my machines internal IP of 10.10.10.17. As I expected, and the reason for opening this ticket in the first place, is that the result is still the same. One running drive share, one attempting to run share who isn't receiving callbacks. Additionally, I've switched to running on Ubuntu now to remove any possible "windows" issues.

### Drive Share 1
```
{debug} [Sat Jul 30 2016 22:12:37 GMT-0500 (CDT)] cleaning bad contacts from routing table
{debug} [Sat Jul 30 2016 22:12:37 GMT-0500 (CDT)] dropping 0 bad contacts from router
{info} [Sat Jul 30 2016 22:12:49 GMT-0500 (CDT)] successfully traversed NAT via UPnP: 73.183.176.104:37607
{info} [Sat Jul 30 2016 22:12:49 GMT-0500 (CDT)] tunnel server bound and port mapped: 37607
{info} [Sat Jul 30 2016 22:12:49 GMT-0500 (CDT)] successfully traversed NAT via UPnP: 73.183.176.104:4941
{info} [Sat Jul 30 2016 22:12:49 GMT-0500 (CDT)] kad node bound and port mapped: 4941
{info} [Sat Jul 30 2016 22:12:49 GMT-0500 (CDT)] node created with nodeID 593e5b624a20034e0d50b22791e09df455972be5
{info} [Sat Jul 30 2016 22:12:49 GMT-0500 (CDT)] resolving seeds from https://api.storj.io
....
(insert lots more traffic of shares/contracts/etc/)
```

### Drive Share 2
```
{info} [Sat Jul 30 2016 22:12:34 GMT-0500 (CDT)] successfully traversed NAT via UPnP: 73.183.176.104:55141
{info} [Sat Jul 30 2016 22:12:34 GMT-0500 (CDT)] tunnel server bound and port mapped: 55141
{info} [Sat Jul 30 2016 22:12:34 GMT-0500 (CDT)] successfully traversed NAT via UPnP: 73.183.176.104:6792
{info} [Sat Jul 30 2016 22:12:34 GMT-0500 (CDT)] kad node bound and port mapped: 6792
{info} [Sat Jul 30 2016 22:12:34 GMT-0500 (CDT)] node created with nodeID a25445b7bec8440178a1e9a51932bf3d8cfdbc2b
{info} [Sat Jul 30 2016 22:12:34 GMT-0500 (CDT)] resolving seeds from https://api.storj.io
...
{debug} [Sat Jul 30 2016 22:12:42 GMT-0500 (CDT)] checking pending rpc callback stack for f99ef751c503b3bb9876b07189bbe78e9b0ed81a
{debug} [Sat Jul 30 2016 22:12:49 GMT-0500 (CDT)] cleaning bad contacts from routing table
{debug} [Sat Jul 30 2016 22:12:49 GMT-0500 (CDT)] dropping 0 bad contacts from router
{debug} [Sat Jul 30 2016 22:13:04 GMT-0500 (CDT)] checking pending rpc callbacks for expirations
{debug} [Sat Jul 30 2016 22:13:34 GMT-0500 (CDT)] cleaning bad contacts from routing table
{debug} [Sat Jul 30 2016 22:13:34 GMT-0500 (CDT)] dropping 0 bad contacts from router
{debug} [Sat Jul 30 2016 22:13:34 GMT-0500 (CDT)] checking pending rpc callbacks for expirations
{debug} [Sat Jul 30 2016 22:13:49 GMT-0500 (CDT)] cleaning bad contacts from routing table
{debug} [Sat Jul 30 2016 22:13:49 GMT-0500 (CDT)] dropping 0 bad contacts from router
{debug} [Sat Jul 30 2016 22:14:04 GMT-0500 (CDT)] checking pending rpc callbacks for expirations
{debug} [Sat Jul 30 2016 22:14:34 GMT-0500 (CDT)] cleaning bad contacts from routing table
{debug} [Sat Jul 30 2016 22:14:34 GMT-0500 (CDT)] dropping 0 bad contacts from router

```

**Comment by utdrmac** [comment]
And yes, I did read it in 4 minutes and said "well, that's not an option. better update the bug report with this info"

**Comment by littleskunk** [comment]
Looks better now. You fixed the first problem. No more timeouts.

Now go on with https://github.com/Storj/core/issues/221#issuecomment-231952955

**Comment by utdrmac** [comment]
Setting both shares to a fixed port (6792 & 4941, as these were the last NAT-UPnP values used per the logs) made things "worse". Now, neither drive share is making connections; RPC timeouts on both sides.

**Comment by littleskunk** [comment]
100% timeouts again?
```
With 100% timeouts you should check port forwarding, firewall, virus scanner and syncronize your clock with a good internet time server like time.nist.gov. 
```

**Comment by utdrmac** [comment]
@littleskunk Fresh install. Removed `/root/.config/Storj Share/` I even set up port 4000 through my router. Disabled NAT/UPnP. Storj running. Public port scanner says 4000 is open. Still getting `missing or empty reply from contact`  Fresh log attached. 
[Drive-0_2016-8-1.log.gz](https://github.com/Storj/storjshare-cli/files/394361/Drive-0_2016-8-1.log.gz)

**Comment by utdrmac** [comment]
@littleskunk Its been 24hrs. No new contracts. Only 1 peer connected. Repeated log lines like this, 100s of times:

```
{info} [Mon Aug 01 2016 18:28:11 GMT-0500 (CDT)] received valid message from {"protocol":"0.7.1","address":"STORJ-CLUS-011.storj.space","port":4300,"nodeID":"3023a7b2656a0c91d3f0e0c237f4ea72fe9f3dd7","lastSeen":1470094091669}
{info} [Mon Aug 01 2016 18:38:11 GMT-0500 (CDT)] attempting to join network via storj://STORJ-CLUS-011.storj.space:4300/3023a7b2656a0c91d3f0e0c237f4ea72fe9f3dd7
{info} [Mon Aug 01 2016 18:38:11 GMT-0500 (CDT)] sending FIND_NODE message to {"protocol":"0.7.1","address":"storj-clus-011.storj.space","port":4300,"nodeID":"3023a7b2656a0c91d3f0e0c237f4ea72fe9f3dd7","lastSeen":1470094691724}
```

ports are open. this is clearly an issue. please re-open this.

**Comment by utdrmac** [comment]
Alright. This looks along the lines of #221
