### ISSUE TITLE
CLI Crash:  No space left on device / Unable to restart CLI after crash

### ISSUE THREAD

**Issue by dogpatchmedia** [Storj/storjshare-cli#142]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 5.0.0
Core:       2.0.0
Protocol:   0.7.1
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Keep running even though the disk is full.

### Actual Behavior

Eventually storjshare-cli will crash if there is no disk space left and it will not start back up.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: /mnt/volume3/storj/farmer.db/1547340.ldb: No space left on device
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/levelup.js:119:34
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16

/dev/xvdd1     257898884 257885340         0 100% /mnt/volume5
/dev/xvdc1     257898884 257896228         0 100% /mnt/volume3
```

### Steps to Reproduce

1. Start storjshare-cli on Ubuntu 14.04 and point it to a directory on a drive that is full. You should get an error about the disk being full and the cli not starting.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-cli/issues/92
