### ISSUE TITLE
We have enough free space true : No space left on device

### ISSUE THREAD

**Issue by utdrmac** [Storj/storjshare-cli#143]
### Package Versions

Replace the values below using the output from `storjshare --version`.

--version is not returning a value after upgrading to latest version.

```
root@drmac-ubuntu:~/.config/Storj Share# storjshare --version
root@drmac-ubuntu:~/.config/Storj Share# echo $?
0
```

### Expected Behavior

Once storj has used up the specified configured space, it should stop accepting contracts.

### Actual Behavior

Actual behavior seems to be that storj continues to believe there is free space. I believe this is related to #131 

```
{debug} [Sun Jul 31 2016 13:44:37 GMT-0500 (CDT)] we have enough free space: true
{error} [Sun Jul 31 2016 13:44:37 GMT-0500 (CDT)] IO error: /opt/storj20gb/farmer.db/088339.ldb: No space left on device

Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sdb1       20511356 20494980         0 100% /opt/storj20gb
```

### Steps to Reproduce

1. Create a 20GB partition
2. Mount partition (ex: /opt/storj20gb)
3. Start storjshare and specify above directory with 20GB
4. Wait for contracts to be fulfilled and space to be used
5. Disk space will be consumed to 100% but storj will continue saying there is space

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-cli/issues/92

Note: 20GB would be 20971520 and not 20511356. ~400MB are missing.

**Comment by utdrmac** [comment]
```
Model: ATA WDC WD10EZEX-08M (scsi)
Disk /dev/sdb: 1000GB
Sector size (logical/physical): 512B/4096B
Partition Table: gpt

Number  Start   End     Size    File system  Name  Flags
 1      1049kB  21.5GB  21.5GB  ext4
 2      21.5GB  43.0GB  21.5GB  ext4


root@drmac-ubuntu:~# df -m /dev/sdb1
Filesystem     1M-blocks  Used Available Use% Mounted on
/dev/sdb1          20031 20015         0 100% /opt/storj20gb

```

**Comment by littleskunk** [comment]
20 GB * 1024 = 20480 MB
20480 MB *1024 = 20971520 KB
20971520 KB * 1024 = 21474836480 Byte

**Comment by utdrmac** [comment]
I know how to do the math. I'm just telling you what all I set as far as options go and what linux is reporting. When I created the partition I specified it as 20480 MB large and then configured storj as a 20GB share.

**Comment by littleskunk** [comment]
If you know the math I don't understand the problem.
Partition size 20480 MB * **1000**
Storj config 20480 MB * **1024**
~400 MB are missing -> #92

**Comment by utdrmac** [comment]
Seems that gparted uses mibibytes. Will recreate partitions.
