### ISSUE TITLE
Failed to discover seeds

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#155]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 5.0.2
Core:         2.2.0
Protocol:   0.7.1
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

Leaving the seed node specifications blank should ALWAYS fine a seed via api.storj.io.

### Actual Behavior

Manually started (4) new nodes this morning and when I went to check on them, discovered only 2 were running.  The other two had "Failed to discover seeds from  : <html>" messages in the log.

Entire log file screen capture below (its short):

http://puu.sh/qEQiU/41407fba75.png

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
This can happen if the configured bridge server does not respond. Workaround by supplying some known seeds in the config.

**Comment by 1credit** [comment]
Understand.  But manually restarting and/or hand coding seeds servers implies extra administrative overhead.  Seeds change, and config files would need to be updated.  Restarting makes for a pretty unreliable service after reboots, especially if running multiple nodes.

Rather than fail, the service should sleep something like 30 seconds and try again, infinitely, logging its efforts as errors of course.

Imagine a situation where dozens of machine restarted after a site power outage, only to fail because the Internet connection was still being established...

**Comment by bookchin** [comment]
You can use PM2 as described in the README to automatically restart the process if it exits to handle this: https://github.com/Storj/storjshare-cli#running-in-the-background

**Comment by 1credit** [comment]
Hmmm, had problems with PM2 handling multiple nodes running on the same box.  Also not happy with the concept of having a program that could go into a restart loop should there be some other reason it aborts.  From a system admin perspective, that is dangerous.

**Comment by bookchin** [comment]
Understood. Perhaps you would open a feature request that describes in more detail the conditions and configuration you'd like to see for retrying entrance into the network?

Just wanted it to be be clear that this is currently expected behavior to exit on failure to connect.
