### ISSUE TITLE
Seed discover retry feature

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#156]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 5.0.2
Core:         2.2.0
Protocol:   0.7.1
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```
### Expected Behavior

Provide a retry mechanism for failed seed node population.  Ideally a parameter could be specified that allowed for a specification such as N times, or Retry-Forever.  Failures should be logged as Errors.
### Actual Behavior

Currently if a connection to api.storj.io fails during initial seeding, the cli application will fail and exit.  This is an administrative headache, especially for those running multiple nodes.

```

```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. ...
2. ...
3. ...

**Comment by phutchins** [comment]
I second this one... Seeing it pop up quite often on one of my farmers.

**Comment by super3** [comment]
This was added in storj-lib, and is pre-configured in storjshare-daemon.
