### ISSUE TITLE
PM2 documentation enhancement

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#157]
### Expected Behavior

Ability to monitor and restart multiple nodes within one environment,
### Actual Behavior

PM2 is currently depended upon to resolve multiple issues, from log rotation to restarting after a failed connection to api.storj.io.  The current PM2 documentation is written for a user wishing to run a single instance of storjshare in an environment.  Since the current implementation of storhshare utilizes at most a single CPU, this is inefficient for users will multiple CPU environments.

Please augment the PM2 documentation to reflect how to run multiple nodes on one server or provide alternative methods for accomplishing that task.  Of particular concern is storjshare's habit of exiting when it is unable to reach api.storj.io.

Note that, at least in the current design, having an external process monitor and restart is REQUIRED if a user wishes to offer a highly available service.  Such a system MUST be capable of differentiating between a recoverable event, such a temporary access issues to api.storj.io, and permanent issues such as invalid config.json files which would result in permanent looping conditions.

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...
```

**Comment by super3** [comment]
PM2 no longer necessary with https://github.com/Storj/storjshare-daemon.
