### ISSUE TITLE
"[error]   undefined"

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#159]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Storjshare:  6.0.1
Core:          3.0.4
Protocol:    0.8.0
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior
Error free startup...

### Actual Behavior

I only had loglevel set to 1, but spotted this in one of many failed nodes:

fspoe node00 # cat port4600.log
{"type":"info","message":"telemetry report {\"storage\":{\"free\":274495370971,\"used\":382535973},\"bandwidth\":{\"upload\":0.19,\"download\":11.97},\"contact\":{\"protocol\":\"0.8.0\",\"address\":\"fspoe.carpenter-farms.us\",\"port\":4600,\"nodeID\":\"e4b4e4e0664d50b98f7f41b1dcb1da138605dff4\",\"lastSeen\":1471645338839},\"payment\":\"1CqdxZemsFmg1A9fm3y1hduwqF5wzBAyKJ\"}","timestamp":"2016-08-19T22:22:18.880Z"}
 [error]  undefined

Retrying would often work.  This is on a very heavily loaded system, so DNS timeouts are a possibility, but hopefully storjshare would die with a more meaningful message.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
https://github.com/Storj/core/issues/358
