### ISSUE TITLE
obj.address is not a function error in PM2 cluster mode

### ISSUE THREAD

**Issue by rrivv** [Storj/storjshare-cli#160]
```
StorjShare: 6.0.1
Core:  3.0.4
Protocol:   0.8.0
Node v4.4.7
Ubuntu 14
Hardware platform: VPS KVM or VPS OpenVZ
```
Get an error when trying to run storjshare in PM2-cluster mode: **obj.address is not a function**.
Allowing **only one instance per js script for cluster mode** (-i 1)

> PM2 App name:storjshare id:0 online
storjshare-0 TypeError: obj.address is not a function
storjshare-0     at Socket.<anonymous> (cluster.js:581:27)
storjshare-0     at Socket.g (events.js:260:16)
storjshare-0     at emitNone (events.js:72:20)
storjshare-0     at Socket.emit (events.js:166:7)
storjshare-0     at startListening (dgram.js:121:10)
storjshare-0     at onHandle (dgram.js:198:9)
storjshare-0     at shared (cluster.js:601:5)
storjshare-0     at Worker.<anonymous> (cluster.js:575:9)
storjshare-0     at process.<anonymous> (cluster.js:736:8)
storjshare-0     at emitTwo (events.js:92:20)
storjshare-0     at process.emit (events.js:172:7)
storjshare-0     at handleMessage (internal/child_process.js:695:10)
storjshare-0     at internal/child_process.js:497:7
storjshare-0     at process.handleConversion.dgram.Native.got (internal/child_process.js:125:7)
storjshare-0     at process.<anonymous> (internal/child_process.js:496:13)
storjshare-0     at emitTwo (events.js:92:20)

```
```
### Steps to Reproduce
pm2 start /usr/lib/node_modules/storjshare-cli/bin/storjshare.js **-i 1** -- start --datadir /home/storjshare --password xxxxxxxx

**Comment by bookchin** [comment]
Nowhere in the provided stack trace is any reference to storjshare-cli or storj-lib, so I must assume that this is a problem with PM2 (either way this feature is not something we can support right now).  Try upgrading PM2 and see if that resolves the issue

**Comment by rrivv** [comment]
with pm2 2.0.18 and node 6.9.1 cluster mode works fine

**Comment by bookchin** [comment]
Oh good! :+1:
