### ISSUE TITLE
State Table Overflow

### ISSUE THREAD

**Issue by vedalken254** [Storj/storjshare-cli#164]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: v6.0.1
Core:   v3.0.4
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

State table stability in modems due to TCP streaming instead of TCP message spamming (HTTP-like or similar to getwork in the bitcoin mining scene back in the day).

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

TCP messages and connections spam modem and router state tables with a bunch of non-terminated connections that are simply waiting to time out. The result is packet loss even with minimal usage of bandwidth. I have noticed that my packet loss spikes as my Pfsense state table hits around 2.5k during Storjshare's random heavy usage periods. I suspect that is around my modem's limit but I have no way to verify this. We need a stratum-like stream for connections, not the cumbersome and overburdening system currently in use. Bridges should link with each other through this streaming connection style as well as with farmers. Farmers should follow their XOR closest nodeid system and use that for establishing connections via the streaming platform. The reason is because most (if not all) modems are hardcoded in their timeout settings for connections. At least stop relying on FIN_WAIT connection statuses if not using this suggestion. Force the client to see the reply FIN and send an RST flag.
EDIT: attached current state summary for my storjshare-cli client's local ip via this puush image:
http://puu.sh/qPcpw/1be99a7b7d.png (IPv4) and this gem is IPv6( http://puu.sh/qPcFr/2e3cdcd09b.png ; do I dare ask why my storjshare-cli client is spamming out UDP connections when forward is set to false?)
```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start Storjshare
2. Allow state table accumulation
3. Packet Loss Occurs due to overloaded state table

**Comment by vedalken254** [comment]
Another Update on the UDP on ipv6 stuff: http://puu.sh/qPcU1/58fcc516bc.png is that same ip a mere minute after stopping storjshare-cli via pm2. Why is storjshare-cli spamming out UDP connections especially when Forward is set to false in config.json?

**Comment by 1credit** [comment]
I fully support this request.  On a small 4 node system, recently restarted, I am seeing:

118 ESTABLISHED connections to bridge servers
397 total connections to bridge servers (difference in FIN-WAIT2 and TIME-WAIT)
160 ESTABLISHED connections overall (bridge and other storj users)
474 total connections overall

I've seen 10X those numbers if I crank up the number of nodes to use more than trivial amounts of CPU.  The ratios remain about the same.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/storjshare-cli/issues/122
