### ISSUE TITLE
Coloring in storjshare-cli

### ISSUE THREAD

**Issue by deadgray** [Storj/storjshare-cli#165]
Please add colors to console output in storjshare-cli client, same way as made in storj client (in core).
error= colors.red
warning = colors.yellow
info = colors.white(default)
info.data_channel_opened = colors.blue

Thanks!

Edit:
core:
![storj-colors-core](https://cloud.githubusercontent.com/assets/20277696/18033107/e4c796ac-6d1a-11e6-9be5-1cae22adb12d.PNG)
cli:
![storj-nocolors-cli](https://cloud.githubusercontent.com/assets/20277696/18033108/ed45139a-6d1a-11e6-8e18-fb55dfad2d12.PNG)

**Comment by littleskunk** [comment]
Storj core cli already has colored output. I did some tests with crontab and nohup. I have seen python colored output that will crash in this special case. Storj core cli was working fine without any crash.

Please add colored output to storjshare-cli the same way: https://github.com/Storj/core/blob/6b20da8f6dcf376490afee9f8c48451eca59092b/bin/storj.js#L33

**Comment by aleitner** [comment]
These logs are new line terminated json so that it can be parsed however you want and piped into whatever you want. We're not looking to add color to this, but feel free to pipe it into something that does!
