### ISSUE TITLE
Storjshare would not create the .storjshare directory in setup

### ISSUE THREAD

**Issue by phutchins** [Storj/storjshare-cli#168]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 6.0.2
Core: 3.1.0
Protocol: 0.8.0
```

Replace the values below using the output from `node --version`.

```
v6.5.0
```

### Expected Behavior

Storj Share should create the parent directory for its config when given a path that does not exist.

### Actual Behavior

Storj Share states "Refusing to overwrite the supplied path" for /home/philip/.storjshare/id_ecdsa but it doesn't actually exist. When I create the .storjshare directory, Share is able to create the id_ecdsa file and continues.

```

```

### Steps to Reproduce

1. Install Storj Share - npm install -g storjshare-cli
2. Run the wizard - storjshare setup
3. Press return at the default for "Enter the path to store your encrypted private key". Make sure that the .storjshare directory does not exist.

This was run on a Raspberry Pi 3b running Ubuntu Mate 16.04.

**Comment by littleskunk** [comment]
Nodejs 6.5.0 is not supported. https://storj.readme.io/docs/storjshare-troubleshooting-guide#wrong-node-version

**Comment by phutchins** [comment]
It has been working just fine on node 6.5.0. The issue described in the doc you shared is not the same issue that I experienced. I will retest in our supported version of node.

**Comment by phutchins** [comment]
Reproduced same results on ubuntu 16.04 with node 4.4.4 which is supported. We're probably simply only creating the directory for the 'configuration and data' dir and not the 'path to store your encrypted private key' dir. 

<img width="981" alt="screen shot 2016-08-30 at 8 50 42 pm" src="https://cloud.githubusercontent.com/assets/1074345/18112146/80bba98e-6ef3-11e6-8a5f-e347ca64c4af.png">
