### ISSUE TITLE
I think my storjshare-cli node is not sending any telemetry info

### ISSUE THREAD

**Issue by fjsanchezgilzarag** [Storj/storjshare-cli#172]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
    StorjShare: 6.0.3
    Core:       3.1.1
    Protocol:   0.8.1

```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

They told me on slack that must find rows like the next one:
    6:36 PM {"type":"info","message":"telemetry report {\"storage\":{\"free\":940528646810,\"used\":158982980966},\"bandwidth\":{\"upload\":53.82,\"download\":183.73},\"contact\":{\"userAgent\":\"3.1.1\",\"protocol\":\"0.8.1\",\"address\":\"STORJ-CLUS-002.storj.space\",\"port\":4000,\"nodeID\":\”xxxxxx\",\"lastSeen\":1473188550181},\"payment\":\”xxxxxxxx\"}","timestamp":"2016-09-06T19:08:54.133Z"}
    
    every 10 mins ish
    37 well more like 5-6

### Actual Behavior

   can't find any row like that in the whole log find. I'm assured to set loglevel to 3 and the telemetry { "enabled" : true " ] in my config.json

```

```

### Steps to Reproduce

just start storjshare-cli and analyze log file. I never find any word like telemetry on it.

On slack "#storjshare" channel they make me several questions and decided should be an issue.

**Comment by bookchin** [comment]
Can you paste your config.json here?

**Comment by fjsanchezgilzarag** [comment]
{

  "keypath": "/home/jive/.storjshare/id_ecdsa",

  "address": "<my Counterparty Address>",

  "storage": {

    "path": "/home/jive/.storjshare",

    "size": 5,

    "unit": "TB"

  },

  "network": {

    "address" : "<my public ip address>",

    "port": 4100,

    "seeds": [],

    "concurrency": 5,

    "opcodes": [

      "0f01020202",

      "0f02020202",

      "0f03020202"

    ],

    "forward":false,

    "tunnels": 3,

    "tunnelport": 4101,

    "gateways": {

      "min": 4102,

      "max": 4104

    }

  },

  "telemetry": {

    "service": "https://status.storj.io",

    "enabled": true

  },

  "loglevel": 3

}

 

 

De: Gordon Hall [mailto:notifications@github.com] 
Enviado el: miércoles, 14 de septiembre de 2016 15:57
Para: Storj/storjshare-cli
CC: fjsanchezgilzarag; Author
Asunto: Re: [Storj/storjshare-cli] I think my storjshare-cli node is not sending any telemetry info (#172)

 

Can you paste your config.json here?

**Comment by littleskunk** [comment]
The speedtest json file is missing. As far as I know the telemetry report will wait for the speedtest.

**Comment by fjsanchezgilzarag** [comment]
And How can I generate that file?

 

De: littleskunk [mailto:notifications@github.com] 
Enviado el: miércoles, 14 de septiembre de 2016 17:09
Para: Storj/storjshare-cli
CC: fjsanchezgilzarag; Author
Asunto: Re: [Storj/storjshare-cli] I think my storjshare-cli node is not sending any telemetry info (#172)

 

The speedtest json file is missing. As far as I know the telemetry report will wait for the speedtest.

**Comment by fjsanchezgilzarag** [comment]
How do you know that my speed file is missing, just seen my config.json?
