### ISSUE TITLE
TypeError: Cannot read property 'bitfield' of undefined

### ISSUE THREAD

**Issue by wyh136** [Storj/storjshare-cli#177]
### Package Versions
StorjShare: 7.0.0-beta
Core:       4.0.0-rc.2
Protocol:   0.8.1

node --version
v4.4.4

d1-11T-0 TypeError: Cannot read property 'bitfield' of undefined
d1-11T-0     at Function.BloomFilter.deserialize (/home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad-quasar/lib/bloomfilter.js:47:18)
d1-11T-0     at Object.callback (/home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad-quasar/lib/quasar.js:362:32)
d1-11T-0     at Transport.RPC._execPendingCallback (/home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/rpc.js:331:17)
d1-11T-0     at /home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/rpc.js:235:12
d1-11T-0     at /home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/rpc.js:305:5
d1-11T-0     at /home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:251:17
d1-11T-0     at /home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:154:25
d1-11T-0     at /home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:248:21
d1-11T-0     at /home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:612:34
d1-11T-0     at Transport.protocol (/home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/hooks/protocol.js:21:14)
d1-11T-0     at /home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:607:21
d1-11T-0     at /home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:246:17
d1-11T-0     at iterate (/home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:146:13)
d1-11T-0     at /home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:157:25
d1-11T-0     at /home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:248:21
d1-11T-0     at /home/phinx/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:612:34

**Comment by bookchin** [comment]
Tracking here: https://github.com/kadtools/kad-quasar/issues/8
