### ISSUE TITLE
LOCK - The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#178]
### Package Versions

```
StorjShare: 7.0.0-beta
Core:       4.0.0-rc.2
Protocol:   0.8.1
```

```
v4.5.0
```

### Expected Behavior

Should not get continual lock messages

### Actual Behavior

Receive continual lock messages

```
{"level":"warn","message":"error in storage manager: IO error: LockFile H:\\.storjshare\\sharddata.kfs\\076.s/LOCK: The process cannot access the file because it is being used by another process.\r\n","timestamp":"2016-09-21T01:25:08.761Z"}
{"level":"warn","message":"error in storage manager: IO error: LockFile H:\\.storjshare\\sharddata.kfs\\076.s/LOCK: The process cannot access the file because it is being used by another process.\r\n","timestamp":"2016-09-21T01:25:08.761Z"}
{"level":"warn","message":"error in storage manager: IO error: LockFile H:\\.storjshare\\sharddata.kfs\\076.s/LOCK: The process cannot access the file because it is being used by another process.\r\n","timestamp":"2016-09-21T01:25:08.761Z"}
{"level":"warn","message":"error in storage manager: IO error: LockFile H:\\.storjshare\\sharddata.kfs\\076.s/LOCK: The process cannot access the file because it is being used by another process.\r\n","timestamp":"2016-09-21T01:25:08.761Z"}
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run storjshare-cli pre-release
2. After a while should notice the above messages in the log

**Comment by computeronix** [comment]
Also this occurs from time to time -- most likely related

{"level":"error","message":"Could not get usedSpace: IO error: LockFile F:\\.storjshare\\sharddata.kfs\\133.s/LOCK: The process cannot access the file because it is being used by another process.\r\n","timestamp":"2016-09-21T01:36:17.502Z"}

**Comment by littleskunk** [comment]
Duplicate https://github.com/Storj/kfs/issues/24
