### ISSUE TITLE
@next Errors (kfs pre-release)

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-cli#179]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare:  7.0.0-beta
Core:           4.0.0-rc.2
Protocol:     0.8.1
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Storjshare runs without throwing errors.
### Actual Behavior

So far, have seen the following "Day 1" errors:

1)  [99570.267917] node[25597]: segfault at 0 ip 000003b3ed79fc13 sp 000003b3db6a7e30 error 4 in leveldown.node[3b3ed780000+7c000]

2)       throw er; // Unhandled 'error' event
      ^

Error: IO error: lock /store/storj/node01/sharddata.kfs/005.s/LOCK: already held by process
(Issue 178)

3)  /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad-quasar/lib/bloomfilter.js:47
    bf.filters[i].bitfield.buffer = new Buffer(filters[i], 'hex');
                 ^

TypeError: Cannot read property 'bitfield' of undefined

(Isssue #177)

4)        throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:5540

All have been seen on various node numbers and network server ports.

<User error - not a bug>

5)  Telemetry reports are not being generated.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Crank up a 100 or so nodes and watch the console and system dmesg log
2. ...
3. ...

**Comment by littleskunk** [comment]
2.) https://github.com/Storj/kfs/issues/24
3.) https://github.com/Storj/storjshare-cli/issues/177
5.) https://github.com/Storj/storjshare-cli/issues/176

**Comment by Puychack** [comment]
3.) [Storj/core/#443](https://github.com/Storj/core/issues/443)

**Comment by bookchin** [comment]
Prepping `v4.0.0-rc.3`: https://github.com/Storj/core/pull/444

**Comment by 1credit** [comment]
Thanks all.  Thinking of this "issue" as more of a punch list of potentially related issues - so appreciate the additional references.

**Comment by 1credit** [comment]
4)  User error, not a bug.

**Comment by bookchin** [comment]
I think everything here is tracked in separate issues now, so i'm closing.
