### ISSUE TITLE
@next allow for checking for update using outdated

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#180]
When using the outdated command

npm outdated -g -depth 1 storjshare-cli@next

No results are returned even though a new version is available.  Can you add an option to allow for the outdated command to work for the beta branch?

An example of it working would display a result of

npm outdated -g -depth 1 storjshare-cli
Package            Current  Wanted  Latest  Location
storjshare-cli  7.0.0-beta   6.0.3   6.0.3  storjshare_location

**Comment by bookchin** [comment]
This is a function of NPM and we have no control over it.
