### ISSUE TITLE
undefined property

### ISSUE THREAD

**Issue by wyh136** [Storj/storjshare-cli#182]
### Package Versions
Farmer: v7.0.0-beta
Core:   v4.0.0-rc.3
Protocol: 0.8.1
node version:v4.4.4

{"level":"error","message":"failed to handle message, reason: Cannot read property 'userAgent' of undefined","timestamp":"2016-09-25T14:24:50.942Z"}

**Comment by super3** [comment]
Please use the issue template. There is almost no info in this issue to be able to reproduce.
