### ISSUE TITLE
Contract no longer open to offers - too slow to respond?

### ISSUE THREAD

**Issue by Redsandro** [Storj/storjshare-cli#185]
### Package Versions

```
StorjShare: 6.0.3
Core:       3.2.3
Protocol:   0.8.1
```

```
Node: v4.6.0
```

### Expected Behavior

Store at least some shards after a while

### Actual Behavior

For the past few days (since I started), I've only been getting _"Contract no longer open to offers"_ messages. Nothing is stored.

I have Gigabit internet which should beat the average by far, but my hardware is probably slow (for power consumption reasons): AMD Fusion E-350 1.6 GHz 2 cores TDP 18 Watt.

Does this mean my hardware is too slow to respond compared to the competition, or could there be software related fixes/tweaks?

```javascript
{
  "keypath": "/home/redsandro/.storjshare/id_ecdsa",
  "address": "**********",
  "storage": {
    "path": "/home/redsandro/.storjshare",
    "size": 3000,
    "unit": "GB"
  },
  "network": {
    "address": "**********",
    "port": 4000,
    "seeds": [],
    "opcodes": [
      "0f01020202",
      "0f02020202",
      "0f03020202",
      "0f01020303",
      "0f02020303",
      "0f03020303"
    ],
    "forward": false,
    "tunnels": 3,
    "tunnelport": 4001,
    "gateways": {
      "min": 4002,
      "max": 4004
    },
    "concurrency": 3
  },
  "telemetry": {
    "service": "https://status.storj.io",
    "enabled": false
  },
  "loglevel": 3
}
```

Does adding more `opcodes` make sense for getting more contracts?

**Comment by super3** [comment]
Please read our [latest blog post](http://blog.storj.io/post/151141372148/how-to-ddos-yourself). There are some network wide issues that we are addressing. We plan on releasing a new version of everything this week. You can follow progress on [Waffle](https://waffle.io/Storj/core). 

I suggest the following: 
1. Wait for the next release, and upgrade when its avaible. 
2. Restart your node. 
3. Delete config, and restart. Might just be at a bad place on the network. 

After we do the upgrade we will be pumping a lot more data into the network again, so your chances of getting contracts will go up a ton.

**Comment by Redsandro** [comment]
Thank you for elaborating on this.
