### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Redsandro** [Storj/storjshare-cli#186]
### Package Versions

```
StorjShare: 6.0.3
Core:       3.2.3
Protocol:   0.8.1
Node:      v4.6.0
```

### Expected Behavior

Set-it-and-forget-it storage rental without noticable impact to the system.
Disk space is cheap, and we all like to farm the unused space. 

### Actual Behavior

Processor power is not so cheap. The `storj-cli` node process often uses 80-100% of the CPU. Every now and then it goes back to around 20%

This is a much more serious issue. Because not only is the thought of wearing out the processor for idealistic reasons or for earning $2 per month a bad one, what's even more troubling is that I cannot seem to do this and watch a movie on my AMD Fusion E-350 1.6 GHz mediacenter at the same time. Movie playback stutters on occasion, and it didn't before I ran the node.

Interestingly, I don't get a lot of contracts. I don't even get an insane amount a lot of messages in the log as one would expect. The farm is only filled with about 50 MB or so. Why does this low profile usage need so much CPU power?

**Comment by littleskunk** [comment]
I will close this issue as publicate. You can read more about it here: http://blog.storj.io/post/151141372148/how-to-ddos-yourself

The issue should be fixed with the new already release version. Please wait for the bridge update (should follow in a few hours) and try again.

**Comment by Redsandro** [comment]
@littleskunk 

Bridge is not a dependence for `storjshare-cli`, so I don't have to update anything else, right?

I'm getting exclusively `Protocol version is incompatible` and `query failed, removing contact for shortlist, reason RPC with ID [...] timed out` messages now. I'm guessing I just have to wait for others to update?

```
StorjShare: 7.0.0
Core:       4.0.0
Protocol:   0.9.0
```

**Comment by littleskunk** [comment]
The protocol version is important. The bridge is running protocol 0.8.0 (http://api.storj.io/). At the moment you are unable to connect to the bridge.

**Comment by Redsandro** [comment]
@littleskunk Ah! So I have to downgrade for now. Thanks for pointing that out.
