### ISSUE TITLE
Repair command not working

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-cli#190]
https://github.com/Storj/storjshare-cli/blob/b6abd22c72e80a9dfc91f6b6c07000574638e491/bin/storjshare.js#L214

Will repair the old farmer.db shards.

**Comment by bookchin** [comment]
@aleitner i think we can probably remove this feature altogether now or just update it to perform the repair on the `contracts.db` and `sharddata.kfs`

**Comment by super3** [comment]
Corresponds to: https://github.com/Storj/storjshare-gui/issues/384
