### ISSUE TITLE
is it working?

### ISSUE THREAD

**Issue by ironlion27** [Storj/storjshare-cli#193]
running in screen giving the following stdout:

> {"level":"info","message":"starting local database replication","timestamp":"2016-10-10T18:07:59.381Z"}
{"level":"info","message":"database replication complete","timestamp":"2016-10-10T18:07:59.436Z"}

over and over again.  I am not receiving any transactions in my IndiSquare wallet that I used in the setup script to receive compensation.  Is it working?

**Comment by littleskunk** [comment]
This is not a support forum. Please open only issues and not support questions. You will find the answer on your question here: https://storj.readme.io/discuss
