### ISSUE TITLE
After last storjshare-cli upgrade I get the error: TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by brizio1971** [Storj/storjshare-cli#195]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 7.0.0-beta
Core:       4.0.0-rc.7
Protocol:   0.8.1```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Please describe the program's expected behavior.

### Actual Behavior

Runninig pm2 start /usr/local/lib/node_modules/storjshare-cli/bin/storjshare.js -- start --password XXXX --datadir /storj/3/.storjshare/

I get this error:
```
storjshare-0 TypeError: Cannot read property 'map' of undefined
storjshare-0     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/network/index.js:661:49
storjshare-0     at Request._callback (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/lib/bridge-client/index.js:1012:5)
storjshare-0     at Request.self.callback (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/request/request.js:187:22)
storjshare-0     at emitTwo (events.js:87:13)
storjshare-0     at Request.emit (events.js:172:7)
storjshare-0     at Request.<anonymous> (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/request/request.js:1048:10)
storjshare-0     at emitOne (events.js:77:13)
storjshare-0     at Request.emit (events.js:169:7)
storjshare-0     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/request/request.js:969:12)
storjshare-0     at emitNone (events.js:72:20)
storjshare-0     at IncomingMessage.emit (events.js:166:7)
storjshare-0     at endReadableNT (_stream_readable.js:921:12)
storjshare-0     at nextTickCallbackWith2Args (node.js:442:9)
storjshare-0     at process._tickDomainCallback (node.js:397:17)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by littleskunk** [comment]
```
StorjShare: 7.0.0-beta
Core:       4.0.0-rc.7
Protocol:   0.8.1
```

Please update `npm install -g storjshare-cli`

Correct version output should be:
```
StorjShare: 7.0.1
Core:       4.0.2
Protocol:   0.9.0
```

That should solve your issue.
