### ISSUE TITLE
 [error]  Failed to get seeds for probe

### ISSUE THREAD

**Issue by bananenwilly** [Storj/storjshare-cli#196]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 7.0.1
Core:       4.0.2
Protocol:   0.9.0
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Launch.

### Actual Behavior

farmer-0 (err):     at process._tickCallback (node.js:356:17)
farmer-0 (err): /home/pi/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:643
farmer-0 (err):       neighbors = result.info['x-network-seeds'].map(self._createContact);
farmer-0 (err):                                                 ^
farmer-0 (err): 
farmer-0 (err): TypeError: Cannot read property 'map' of undefined
farmer-0 (err):     at /home/pi/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/index.js:643:49
farmer-0 (err):     at Request._callback (/home/pi/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/lib/bridge-client/index.js:995:5)
farmer-0 (err):     at Request.self.callback (/home/pi/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/request/request.js:187:22)
farmer-0 (err):     at emitTwo (events.js:87:13)
farmer-0 (err):     at Request.emit (events.js:172:7)
farmer-0 (err):     at Request.<anonymous> (/home/pi/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/request/request.js:1044:10)
farmer-0 (err):     at emitOne (events.js:77:13)
farmer-0 (err):     at Request.emit (events.js:169:7)
farmer-0 (err):     at IncomingMessage.<anonymous> (/home/pi/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/request/request.js:965:12)
farmer-0 (err):     at emitNone (events.js:72:20)
farmer-0 (err):     at IncomingMessage.emit (events.js:166:7)
farmer-0 (err):     at endReadableNT (_stream_readable.js:913:12)
farmer-0 (err):     at nextTickCallbackWith2Args (node.js:442:9)
farmer-0 (err):     at process._tickCallback (node.js:356:17)

```

farmer-0 (out): {"level":"warn","message":"failed to map port for tunserver: timeout","timestamp":"2016-10-12T13:03:35.289Z"}
farmer-0 (out): {"level":"info","message":"clock is synchronized with ntp, delta: 73","timestamp":"2016-10-12T13:03:35.378Z"}
farmer-0 (out):  [error]  Failed to get seeds for probe
farmer-0 (out): {"level":"info","message":"you are configured to tunnel up to 0 connections","timestamp":"2016-10-12T13:04:08.432Z"}
farmer-0 (out): {"level":"error","message":"telemetry reporter failed, reason: Cannot read property 'getNodeID' of undefined","timestamp":"2016-10-12T13:04:08.645Z"}
farmer-0 (out): {"level":"warn","message":"you are not publicly reachable, trying traversal strategies...","timestamp":"2016-10-12T13:04:08.681Z"}
farmer-0 (out): {"level":"warn","message":"could not connect to NAT device via UPnP: 32525","timestamp":"2016-10-12T13:04:10.505Z"}
farmer-0 (out): {"level":"info","message":"node created with nodeID 394cb8b61dc17cdbfae68e27f53a08366ecc1a61","timestamp":"2016-10-12T13:04:10.567Z"}
farmer-0 (out): {"level":"warn","message":"could not connect to NAT device via UPnP: 48211","timestamp":"2016-10-12T13:04:10.583Z"}
farmer-0 (out): {"level":"warn","message":"failed to map port for tunserver: timeout","timestamp":"2016-10-12T13:04:10.584Z"}
farmer-0 (out): {"level":"info","message":"clock is synchronized with ntp, delta: 80","timestamp":"2016-10-12T13:04:10.676Z"}
farmer-0 (out):  [error]  Failed to get seeds for probe
farmer-0 (out): {"level":"info","message":"you are configured to tunnel up to 0 connections","timestamp":"2016-10-12T13:05:13.977Z"}
farmer-0 (out): {"level":"error","message":"telemetry reporter failed, reason: Cannot read property 'getNodeID' of undefined","timestamp":"2016-10-12T13:05:14.188Z"}
farmer-0 (out): {"level":"warn","message":"you are not publicly reachable, trying traversal strategies...","timestamp":"2016-10-12T13:05:14.222Z"}
farmer-0 (out): {"level":"warn","message":"could not connect to NAT device via UPnP: 32525","timestamp":"2016-10-12T13:05:16.043Z"}
farmer-0 (out): {"level":"info","message":"node created with nodeID 394cb8b61dc17cdbfae68e27f53a08366ecc1a61","timestamp":"2016-10-12T13:05:16.104Z"}
farmer-0 (out): {"level":"warn","message":"could not connect to NAT device via UPnP: 34938","timestamp":"2016-10-12T13:05:16.119Z"}
farmer-0 (out): {"level":"warn","message":"failed to map port for tunserver: timeout","timestamp":"2016-10-12T13:05:16.120Z"}
farmer-0 (out): {"level":"info","message":"clock is synchronized with ntp, delta: 79","timestamp":"2016-10-12T13:05:16.211Z"}


```

**Comment by bookchin** [comment]
This is an issue with the bridge connectivity to the database. Hang tight while we resolve the infrastructure issue.
