### ISSUE TITLE
CLI leaking memory

### ISSUE THREAD

**Issue by CJClaude** [Storj/storjshare-cli#204]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 7.0.1
Core:       4.0.6
Protocol:   0.9.1

```

Replace the values below using the output from `node --version`.

```
v4.6.0
```
### Expected Behavior

Storjshare process utilizes a consistant and realtively static amount of memory. 
### Actual Behavior

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 9171 storj     20   0 1990972 417100   8320 S  37.5 10.3 102:52.28 node
12492 storj     20   0 2542792 258752   7592 S  37.2  6.4  86:39.45 node
 9996 storj     20   0 2007132 164692   8180 S  30.2  4.1 136:07.68 node
14166 storj     20   0 2232180 281380   8140 R  29.2  6.9  43:29.22 node
18254 storj     20   0 2233452 318212   8536 S  24.3  7.9 111:43.41 node
11663 storj     20   0 3450320 343356   8008 S  17.3  8.5  73:13.86 node
 8411 storj     20   0 3299488 242952   8228 S  15.3  6.0 139:21.56 node
 1983 storj     20   0 3360820 369216   8096 S  13.3  9.1  86:05.43 node
 7664 storj     20   0 1978312 240436   7632 R  12.6  5.9 191:14.30 node
13331 storj     20   0 1483536 139784   6832 S  10.3  3.5 112:29.53 node
19011 storj     20   0 1506116 116048   8232 S   7.0  2.9  17:21.05 node
15006 storj     20   0 2895520 231752   7016 S   2.0  5.7 121:08.58 node
15836 storj     20   0 2051504 177420   7284 S   0.0  4.4  11:26.90 node
16664 storj     20   0 1566040 115972   7496 S   0.0  2.9   9:30.52 node
17420 storj     20   0 1543080 135444   8052 S   0.0  3.3  18:37.81 node
19832 storj     20   0 1539716 151544   6180 S   0.0  3.7  21:31.31 node
```

Note that memory usage is relatively independant of CPU time consumed, but varies by a factor of around 2.  On another system, I see the virtual size exceed 5GB.  Note these totals likely consist of the sum of multiple threads.

Temporarly work-around is to restart all the nodes every few hours, which will ultimately impact reputation, or have the system swap to death.
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. Crank up one or more nodes and watch the memory size grow.
2. ...
3. ...

**Comment by CJClaude** [comment]
Just updating:  This is still happening at StorjShare 8.0.0, Core 5.1.0, Protocol 0.10.0, with Node V6.9.1:

http://puu.sh/sgPfn/76729f2d81.png

**Comment by WilhelmGGW** [comment]
Same situation for the GUI. Issue found here: https://github.com/Storj/storjshare-gui/issues/450

**Comment by littleskunk** [comment]
I found one memory leak and created a new issue https://github.com/Storj/core/issues/566

I will try to find more but it is difficult to detect memory leaks. At some point I have to give up and wait for a fix. That way I can detect the remaining leaks better.

**Comment by CJClaude** [comment]
Finding one is a major accomplishment!

**Comment by bookchin** [comment]
https://github.com/Storj/storjshare-cli/releases/tag/v9.0.0
