### ISSUE TITLE
Failed to join the network

### ISSUE THREAD

**Issue by qbsterr** [Storj/storjshare-cli#208]
### Package Versions

`storjshare --version`.

StorjShare: 7.0.3
Core:       4.1.0
Protocol:   0.9.1

Replace the values below using the output from `node --version`.

```
v7.0.0
```

### Actual Behaviour

[error] Failed to join the network

Every 15 minutes i have got same error and exit 

Not sure why i got 7.0.3 farmer version where actual is 7.0.2

Log:
{"level":"debug","message":"removing contact {\"userAgent\":\"4.1.0\",\"protocol\":\"0.9.1\",\"address\":\"pspoe.carpenter-farms.us\",\"port\":4690,\"nodeID\":\"80e014cc8d22366ca5ac2a0e7b9a3b5bb0e49163\",\"lastSeen\":1477806708113}","timestamp":"2016-10-30T05:52:18.104Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `adf9ca78a52697b66bbc404c9ef0a4b2ac071588` timed out","timestamp":"2016-10-30T05:52:18.104Z"}
{"level":"debug","message":"removing contact {\"userAgent\":\"4.1.0\",\"protocol\":\"0.9.1\",\"address\":\"pspoe.carpenter-farms.us\",\"port\":4690,\"nodeID\":\"80e014cc8d22366ca5ac2a0e7b9a3b5bb0e49163\",\"lastSeen\":1477806708112}","timestamp":"2016-10-30T05:52:18.104Z"}
{"level":"warn","message":"rpc call 9e5c84f693bc9db5f69564498cc510b91afba875 timed out","timestamp":"2016-10-30T05:52:18.104Z"}
{"level":"debug","message":"removing contact {\"userAgent\":\"4.1.0\",\"protocol\":\"0.9.1\",\"address\":\"003c.storjlt.xyz\",\"port\":10301,\"nodeID\":\"f2c2be12214b4a800abc289c4013c886dbf707e0\",\"lastSeen\":1477806708138}","timestamp":"2016-10-30T05:52:18.104Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `9e5c84f693bc9db5f69564498cc510b91afba875` timed out","timestamp":"2016-10-30T05:52:18.104Z"}
{"level":"debug","message":"removing contact {\"userAgent\":\"4.1.0\",\"protocol\":\"0.9.1\",\"address\":\"003c.storjlt.xyz\",\"port\":10301,\"nodeID\":\"f2c2be12214b4a800abc289c4013c886dbf707e0\",\"lastSeen\":1477806708138}","timestamp":"2016-10-30T05:52:18.104Z"}
{"level":"debug","message":"finished iteration, handling results","timestamp":"2016-10-30T05:52:18.104Z"}
{"level":"warn","message":"failed to connect to seed storj://pspoe.carpenter-farms.us:4690/80e014cc8d22366ca5ac2a0e7b9a3b5bb0e49163","timestamp":"2016-10-30T05:52:18.105Z"}
 [error]  Failed to join the network

Can you help ?

**Comment by littleskunk** [comment]
Clock out of sync for more than 15 seconds. You should see the ntp delta at the beginning of your log.
