### ISSUE TITLE
Memory could not be written

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-cli#210]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: v7.0.2
```

Replace the values below using the output from `node --version`.

```
v4.6.1
```
### Expected Behavior

Please describe the program's expected behavior.
### Actual Behavior

![screenshot2](https://cloud.githubusercontent.com/assets/11735738/19836990/892999e0-9eb0-11e6-93b1-e01b0cb0db42.png)
### Steps to Reproduce

Run a Storjshare CLI instance on a USB PC with 2GB ram for a few days with 20GB of shards accumulation.

**Comment by bookchin** [comment]
What is this EXE you are running? We do not ship a windows executable for storjshare-cli.

**Comment by MeijeSibbel** [comment]
@bookchin , I am just running both storjshare GUI and CLI on this machine, no other software.

**Comment by bookchin** [comment]
Okay, I'm just confused about why you are reporting an issue to the CLI with a screenshot of an alert from `Storj Share.exe`, since we do not ship an executable like that for the CLI.

Did you mean to open this in the GUI repository?

**Comment by MeijeSibbel** [comment]
My apologies for the confusion. I opened it in Storjshare-CLI because i got the error when only storjshare-CLI was running. From your comment it probably looks like Storjshare-GUI might have not closed correctly and was thus still running in the background, that could explain this .EXE error. I will close the issue for now until it appears again.
