### ISSUE TITLE
[FEATURE] Display number of contracts

### ISSUE THREAD

**Issue by lakewik** [Storj/storjshare-cli#211]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 7.0.3
Core:       4.1.0
Protocol:   0.9.1

```

Replace the values below using the output from `node --version`.

```
v4.4.4
```
### Expected Behavior

Contracts number can be saved to config file like GUI version, or can be displayed by excuting `storjshare --get-contracts-number` or similar
### Actual Behavior

The only way to count the number of contracts is manually count the lines in files in contracts.db directory

```

```

**Comment by littleskunk** [comment]
GUI user see the contract number increasing but they don't get paid for contracts. They only get paid for used space. -> Number of contracts is more or less useless. Why do you need this useless information?

**Comment by lakewik** [comment]
@littleskunk I did not know that it is useless
