### ISSUE TITLE
Failed instalation on Debian 7

### ISSUE THREAD

**Issue by ekaitz-zarraga** [Storj/storjshare-cli#215]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: N/A
Core:   N/A
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

The program is installed successfully following the README.md

### Actual Behavior

Installation fails with the following errors:
```
# npm install -g storjshare-cli
npm WARN engine storj-lib@5.1.0: wanted: {"node":"^6.9.1"} (current: {"node":"4.4.4","npm":"2.15.1"})
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
 
> secp256k1@3.2.2 install /root/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

Error: EACCES: permission denied, scandir '/root/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/secp256k1'
    at Error (native)
```

### Steps to Reproduce

Follow the steps on the README.md of the project on a Debian 7.11 machine.

**Comment by littleskunk** [comment]
You are running the installation as root! If you are sure you would like to do that you have to add --unsafe-perm. It is recommended to run it as root. Better create a new user for storj.

**Comment by ekaitz-zarraga** [comment]
Yeah! My fault, sorry!
Now is up and running!
Thank you for the fast response.
