### ISSUE TITLE
exchange-report.js:13 function ExchangeReport(options = {}) {

### ISSUE THREAD

**Issue by d2s4** [Storj/storjshare-cli#216]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: v8.0.0
Core:   v5.1.1
OS: Windows 10 x64
```

Replace the values below using the output from `node --version`.

```
v4.6.2
```

### Expected Behavior

Please describe the program's expected behavior.

### Actual Behavior

![2016-11-15_11-43-12](https://cloud.githubusercontent.com/assets/19560199/20293421/c8f7563c-ab28-11e6-9f88-d00e207bf1f8.png)

![2016-11-15_11-47-25](https://cloud.githubusercontent.com/assets/19560199/20293455/50e9f50e-ab29-11e6-9ded-cf5bf7f213db.png)

**Comment by d2s4** [comment]
Decision: https://nodejs.org/dist/v6.9.1/win-x64/node.exe

**Comment by braydonf** [comment]
Related: https://github.com/Storj/storjshare-cli/pull/214

**Comment by bookchin** [comment]
Depends node 6.9.1
