### ISSUE TITLE
Error: IO error already held by process

### ISSUE THREAD

**Issue by wyh136** [Storj/storjshare-cli#218]
### Package Versions

`storjshare --version`.

```
StorjShare: 8.0.0
Core:       5.1.0
Protocol:   0.10.0
```

`node --version`.

```
v6.9.1
```

### Expected Behavior

Change the log level in config.json and restarted.

### Actual Behavior

17|d5      | Error: IO error: lock /home/phinx/disks/d5/.storjshare/sharddata.kfs/151.s/LOCK: already held by process
17|d5      |     at Error (native)

```

```

### Steps to Reproduce

Change the log level in config.json and restarted

**Comment by lakewik** [comment]
#191

**Comment by CJClaude** [comment]
Seeing a LOT of these today on a server running 64 nodes.  Runing 8.0.0/5.1.2/0.10.0

http://puu.sh/sq2nu/b2ccc4f1d3.png

**Comment by bookchin** [comment]
duplicate: https://github.com/Storj/kfs/issues/39
