### ISSUE TITLE
Auto building on hub.docker.com and proper docs

### ISSUE THREAD

**Issue by iBobik** [Storj/storjshare-cli#221]
I want to farm and install Storj by Docker, but it is not intuitive what an how to use it.

Usually it works like this in Docker world:

1. I will look for Docker instructions in README on GitHub where should be example for `docker pull`, `docker run` and basic configuration.
2. If not and I see Dockerfile in the repo I will try to search for a project on hub.docker.com with a proper README and auto builds (because it is safer).

This project have no repo on the Hub (nothing connected with this repo = auto build) and in namespace "storj*", so for Docker users there is no trustworthy image what we can use without much thinking.

**Comment by super3** [comment]
@iBobik Storjshare-cli was deprecated. You will need to re-open this issue on https://github.com/Storj/storjshare-daemon.
