### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by d2s4** [Storj/storjshare-cli#222]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 8.0.0
Core:       5.1.2
Protocol:   0.10.0
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

Help ME
![default](https://cloud.githubusercontent.com/assets/19560199/20648081/d9b359b6-b4cf-11e6-9535-381c65647933.jpg)

**Comment by d2s4** [comment]
OS: Windows 10 x64 (10.0.10586)

StorjShare: 8.0.0
Core:       5.1.2
Protocol:   0.10.0

Python 2.7.11

[27.11.2016.txt](https://github.com/Storj/storjshare-cli/files/614781/27.11.2016.txt)


What else do I need to provide?
Falls are repeated regularly = (

**Comment by bookchin** [comment]
Looks related to memory usage - maybe a leak or maybe insufficient RAM available. How much RAM is available to your system? What other processes are running? How much memory is storjshare using when it starts vs. before this happens?

**Comment by d2s4** [comment]
16GB RAM system; storjshare processes 780MB RAM
![default](https://cloud.githubusercontent.com/assets/19560199/20650489/26f7ad08-b502-11e6-930a-d9410998e67b.jpg)
![2](https://cloud.githubusercontent.com/assets/19560199/20650490/26f894f2-b502-11e6-87ab-cf842ccb5797.jpg)

**Comment by littleskunk** [comment]
Logfile full of data channels. Duplicate: https://github.com/Storj/core/issues/566

@d2s4 please join us on https://community.storj.io/ and contact me channel storjshare. I would like to try to reproduce the data channel spam. Even if we fix the memory leak it is very unlikely that you open 2000 data channels in 1 minute.

**Comment by d2s4** [comment]
conflict caused Ethereum Wallet MIST
