### ISSUE TITLE
localhost:80

### ISSUE THREAD

**Issue by deadgray** [Storj/storjshare-cli#231]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 9.0.3
Core:       6.0.5
Protocol:   1.0.0

```

Replace the values below using the output from `node --version`.

```
v6.9.1
```
Really, what storjshare-cli could want to get from localhost's www?
```
{"level":"warn","message":"error returned from remote host: connect ECONNREFUSED 127.0.0.1:80","timestamp":"2016-12-10T15:58:44.473Z"}
```

**Comment by littleskunk** [comment]
error returned from **remote host**

You are the one sending localhost as your own contact information.
