### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by deadgray** [Storj/storjshare-cli#234]
### Package Versions

```
StorjShare: 9.0.5
Core:       6.0.8
Protocol:   1.0.0

```

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)

```

### Steps to Reproduce

1. Run
2. Wait
3. Error

**Comment by braydonf** [comment]
There have also been ECONNRESET when uploading from https://github.com/Storj/core-cli

**Comment by super3** [comment]
@deadgray storjshare-cli is deprecated. If this issue persists please make a new issue in https://github.com/Storj/storjshare-daemon.
