### ISSUE TITLE
Consistent memory requirement growth for actively receiving nodes

### ISSUE THREAD

**Issue by CJClaude** [Storj/storjshare-cli#235]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 9.0.5
Core:       6.0.8
Protocol:   1.0.0

```

Replace the values below using the output from `node --version`.

```
V6.9.1
```

### Expected Behavior

Consistant and stable memory usage.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Launched a brand new nodeid process and monitored its memory usage and shard accumulation for over 14 hours (until it died due to unrelated causes):

Hour  Virtual Resident Shards
1    1.26GB  0.138GB 323K
2    1.41GB  0.278GB 5.8M
3    1.53GB  0.393GB 8.6M
4    1.73GB  0.535GB  58M
5    1.85GB  0.633GB 158M
6    2.05GB  0.771GB 336M
7    2.16GB  0.859GB 487M
8    2.28GB  0.925GB 644M
9    2.67GB  1.003GB 811M
10  2.75GB  1.040GB 906M
11  2.86GB  1.079GB 1.1GB
12  2.89GB  1.074GB 1.2GB  (slight drop in resident memory likely due to OS kernel management)
13  3.07GB  1.126GB 1.3GB

Note that memory demand increases actually exceeded download shard space for several hours.

Log level 3 file available, but is 436MB in size (41MB compressed). Heapdumps available to known Storj developers.


```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Launch a new nodeid and track process memory usage by hour
2. 
3. ...

**Comment by CJClaude** [comment]
For what it worth, I have been seeing rare, but occassional, Linux kernel errors reporting possible SYN flooding from Storj network ports.

**Comment by deadgray** [comment]
I've seen that my nodes take more than 4GB of RAM easily

**Comment by CJClaude** [comment]
Good news is that I'm NOT seeing this with 9.0.6, at least not yet.  Will wait a few days before closing.

**Comment by super3** [comment]
@CJClaude @deadgray Storjshare-CLI is deprecated. Let me know if this issue persists in Storjshare-Daemon. @CJClaude Sounds like its fixed from your last message.
