### ISSUE TITLE
Can't set an SMB-mounted share as a storage location

### ISSUE THREAD

**Issue by jcs224** [Storj/storjshare-cli#243]
### Package Versions

```
StorjShare: 9.0.8
Core:       6.0.11
Protocol:   1.0.0
```

```
node v7.2.1
```

### Expected Behavior

Fire up StorjShare and start farming!

### Actual Behavior

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: /media/nas_storj/.storjshare/contracts.db: Invalid argument
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/levelup/lib/levelup.js:119:34
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

### Steps to Reproduce

This is an official issue from the Reddit post (not mine)
https://www.reddit.com/r/storj/comments/5d8wbi/cant_start_storj/

Is this the result of not being able to use a SMB-mounted drive as a data storage location? The original poster said once he used his regular hard drive, it solved the issue.

**Comment by littleskunk** [comment]
https://storj.readme.io/docs/storjshare-troubleshooting-guide#section-wrong-node-version

**Comment by jcs224** [comment]
Well, I fixed it, but not by changing the Node version. Using iSCSI seemed to do the trick.
