### ISSUE TITLE
any benchmark period

### ISSUE THREAD

**Issue by modxcustomize** [Storj/storjshare-cli#244]
Hi
could you possible let us know if there is any benchmark period?

I mean I have launched a farm a few days ago and can see contracts but they use just something about 197kbytes instead of a bigger size allocated

`{
  "keypath": "/my-path-to-my-external-hdd/id_ecdsa",
  "address": "1xxxxxx-my-wallet-at-counterwallet.io",
  "storage": {
    "path": "/my-path-to-my-external-hdd",
    "size": 999,
    "unit": "TB"
  },
  "network": {
    "address": "127.0.0.1",
    "port": 4000,
    "seeds": [],
    "opcodes": [
      "0f01020202",
      "0f02020202",
      "0f03020202"
    ],
    "forward": true,
    "tunnels": 3,
    "tunnelport": 4001,
    "gateways": {
      "min": 4002,
      "max": 4004
    },
    "concurrency": 3
  },
  "telemetry": {
    "service": "https://status.storj.io",
    "enabled": false
  },
  "loglevel": 3
}`

I am not sure if I may put the logs here as it shows the hosts and IPs of connections which appear to be those hosting contracts, sorry...  One thing I should say the lines go with green status, it's good right?

Just a note: I am using the pm2 for launching the storjshare and it shows that the process is up for more then 5D.

Thus I am thinking that it does not use all size of allocated space until some certain benchmark is finished, right?

Looking forward to your feedback
Many thanks in advance

**Comment by littleskunk** [comment]
If you have any questions please use https://community.storj.io
