### ISSUE TITLE
"Error: Could not locate the bindings file" at startup

### ISSUE THREAD

**Issue by bananenwilly** [Storj/storjshare-cli#246]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
query not possible
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Startup

### Actual Behavior

pi@pi ~ $ storjshare
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
/home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/build/leveldown.node
 → /home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/build/Debug/leveldown.node
 → /home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/build/Release/leveldown.node
 → /home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/out/Debug/leveldown.node
 → /home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/Debug/leveldown.node
 → /home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/out/Release/leveldown.node
 → /home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/Release/leveldown.node
 → /home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/build/default/leveldown.node
 → /home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/compiled/6.9.1/linux/arm/leveldown.node
    at bindings (/home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/kfs/lib/s-bucket.js:4:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

```

```

### Steps to Reproduce

Startup.

Installed the software with 

pi@pi ~ $ npm install -g storjshare-cli
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/home/pi/.nvm/versions/node/v6.9.1/bin/storjshare -> /home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/bin/storjshare.js
/home/pi/.nvm/versions/node/v6.9.1/lib
└─┬ storjshare-cli@9.0.8 
  └─┬ storj-lib@6.0.11
    ├── jsen@0.6.4  (git://github.com/bugventure/jsen.git#9e57a9d653ff4ea47d364fc37da0f1659bfb8e89)
    └── ntp-client@0.5.5  (git://github.com/bookchin/node-ntp-client.git#64a1d2318284578b90f388565de7c4b5a2441233)

No further errors.

**Comment by super3** [comment]
@bananenwilly Storjshare-cli has be deprecated. Please run https://github.com/Storj/storjshare-daemon and see if this error occurs again.
