### ISSUE TITLE
permission denied, open '/tmp/speedtest.json'

### ISSUE THREAD

**Issue by alphaonex86** [Storj/storjshare-cli#53]
### Package Versions

```
Farmer: v2.2.3
Core:   v0.6.3
Node: v4.4.1
```

### Expected Behavior

Don't do
  permission denied, open '/tmp/speedtest.json'
When I start with 2x user different on same computer

### Actual Behavior

  permission denied, open '/tmp/speedtest.json'

### Steps to Reproduce

Start storjfarm on 2 different user on linux

**Comment by gordonwritescode** [comment]
We can fix this by simply postfixing the tmpfile with the owner's node id. Will issue fix next week.
