### ISSUE TITLE
README link is 404

### ISSUE THREAD

**Issue by zotify** [Storj/storjshare-cli#58]
### Steps to Reproduce

1. Goto the "Configuration" section of the README
2. click the [Abstract Interfaces](http://storj.github.io/core/tutorial-abstract-interfaces.html) link

Actual result: 404 error

Expected: a page to read about the configuration file.

At the moment I can't seem to find any documentation about how to configure `storjshare`.

**Comment by gordonwritescode** [comment]
Thanks, removed. We are working on a central documentation source for these projects now.
