### ISSUE TITLE
Running storjshare did not create a configuration file

### ISSUE THREAD

**Issue by zotify** [Storj/storjshare-cli#59]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: v3.0.3
Core:   v0.6.14
```

Replace the values below using the output from `node --version`.

```
v6.2.0
```

### Expected Behavior

Using `storjshare` will create a default configuration file.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
No configuration file was created.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run `storjshare`

**Comment by littleskunk** [comment]
Please try again with node version 4.X

**Comment by gordonwritescode** [comment]
Then after the first run wizard, it's `$HOME/.storjshare` by default.

**Comment by super3** [comment]
@zotify Where you able to get things working?

**Comment by super3** [comment]
@zotify Been a couple of days, if you were not able to fix it we can reopen the issue.

**Comment by super3** [comment]
@zotify Let me know if the issue has not been resolved and we can reopen.
