### ISSUE TITLE
storjshare-cli crashing with "Could not locate renter for offer"

### ISSUE THREAD

**Issue by martinbehrens** [Storj/storjshare-cli#60]
### Package Versions
```
Farmer: v3.0.4
Core:   v0.6.15
Node: v4.4.4
```
### Expected Behavior

Storjshare-cli being stable in terms of not crashing.

### Actual Behavior

Storjshare-cli just crashes with:

`{"level":"info","message":"received valid message from {\"protocol\":\"0.6.15\",\"address\":\"xxx.xxx.xxx.xxx\",\"port\":4323,\"nodeID\":\"364d0f5a80baa1d9668befa66f1b712761657ce7\",\"lastSeen\":1463761424651}","timestamp":"2016-05-20T16:23:44.652Z"}
{"level":"info","message":"replying to message to dad513298435d3001477b7f880024258971fe438","timestamp":"2016-05-20T16:23:44.658Z"}
{"level":"warn","message":"rpc call 16bd193d103144506fba59e2405a3f3ed1ebc3b4 timed out","timestamp":"2016-05-20T16:23:44.837Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `16bd193d103144506fba59e2405a3f3ed1ebc3b4` timed out","timestamp":"2016-05-20T16:23:44.839Z"}
{"level":"error","message":"Could not locate renter for offer","timestamp":"2016-05-20T16:23:44.842Z"}
/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/router.js:154
  return contact.nodeID === nodeID ? contact : null;
                ^

TypeError: Cannot read property 'nodeID' of undefined
    at Router.getContactByNodeID (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/kad/lib/router.js:154:17)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/interfaces/farmer.js:143:22
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/storage/adapters/level/index.js:83:7
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/levelup.js:258:9`

### Steps to Reproduce

Just run the program and wait until it happens. This is the config in use (all ports are being forwarded):

`{ 
  "keypath": "/mnt/sda/storj/key",
  "address": "payout.address",
  "storage": {
    "path": "/mnt/sda/storj/storjshare",
    "size": 6000,
    "unit": "GB"
  },
  "network": {
    "address": "publicly.reachable.ip.address",
    "port": 4000,
    "seeds": [
      "storj://api.storj.io:8443/78cfca0e01235db817728aec056d007672ffac63"
    ],
    "opcodes": [
      "0f01020202",
      "0f02020202",
      "0f03020202"
    ],
    "forward": true,
    "tunnels": 2,
    "tunnelport": 4002,
    "gateways": {
      "min": 4004,
      "max": 4005
    }
  },
  "telemetry": {
    "service": "https://status.storj.io",
    "enabled": false
  }
}
`

**Comment by gordonwritescode** [comment]
Need to update dependencies, see https://github.com/Storj/core/issues/112

Easiest way is to simply reinstall.
