### ISSUE TITLE
Size limit did not work

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/storjshare-cli#63]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: v3.0.5
Core:   v0.6.16
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```

### Expected Behavior

The farmer stop taking contracs if the size limit is reached.

### Actual Behavior

The farmers ignores the size limit from `config.json`.

```
duck@vlan2-farmer:/mnt/disk1/1Gtpb_1/farmer.db$ du -h
14G     .
duck@vlan2-farmer:/mnt/disk1/1Gtpb_1/farmer.db$ head ../config.json
{
  "keypath": "/mnt/disk1/1Gtpb_1/id_ecdsa",
  "address": "xxxxxxxxx",
  "storage": {
    "path": "/mnt/disk1/1Gtpb_1",
    "size": 10,
    "unit": "GB"
  },
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Set a size limit in `config.json`
2. Wait until there is more space used than set as in `config.json`

**Comment by gordonwritescode** [comment]
I was wondering who would be the first to realize that property is ignored. Needs to be implemented in core, can you open an issue there too?

**Comment by gordonwritescode** [comment]
This will go away magically after the above is resolved.
