### ISSUE TITLE
Feature: Control logging level in config.json file

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/storjshare-cli#64]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: v0.4.3
Core:   v0.6.16
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```

### Expected Behavior

I expect a more granular loggin, if everything runs fine there is no reason to put everything in the logs/console output, it would be better to place only error and warning in a normal/default log level. In this case is it possible to find problems faster, which are not visible in the current mass of info messages.

Loglevel like 

1. Error
2. Warning
3. Info
4. Debug 

would be nice.

### Actual Behavior

The logging is extrem chatty. I am using pm2 which creates automatically logfiles, this files grows fast up to some gigabytes, which takes place and i/o resources.

**Comment by gordonwritescode** [comment]
This is already implemented in the back, so for now you can workaround by passing 0-5 to the logger here: https://github.com/Storj/storjshare-cli/blob/master/bin/farmer.js#L383
