### ISSUE TITLE
Performance decreasing with growing amount of shards (leveldb stalling)

### ISSUE THREAD

**Issue by CzBaer** [Storj/storjshare-cli#69]
### Package Versions
```
Farmer: v3.0.6
Core:   v0.6.16
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

It should be possible to write data (shards) in wire speed (4MB/s in my case) to HDD without  stalling. 

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

My setup: 
 128G RAM, Freenas 9.10, Data on 2X WD Red 6TB ZFS stripe dataset (actual data size 340G)
 Internet connection: 37Mbit/s down/10Mbit/s up

When data comes at full rate (around 4Mbyte/s) I can see in the leveldb LOG file that it can not move the data fast enough from level-0 to the next levels, as it is busy moving data away from level-1 and higher (compaction).  From my understanding, during that time it isn't even possibel to read data and therefore makes the application unresponsive. I remeber seeing this the first time when I reached about 200GB. I've attached one part of the farmer.db/LOG where you can see more or less the issue.
The interesting part starts with "Too many L0 files; waiting..." and ends where the 12 files were finally moved to level-1.
```
farmer.db/LOG:
[farmer.db_LOG.txt](https://github.com/Storj/storjshare-cli/files/298854/farmer.db_LOG.txt)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Let your leveldb grow more than 250GB and feed it with a steady data stream ;-)
2. This might help understand: https://github.com/facebook/rocksdb/issues/210
Yes, I know, they are speaking about SSD drives and 160GB of data, but the outcome is: the more data the slower it will get and most of us will be using normal consumer HDDs and expect a couple of TB data.

**Comment by bookchin** [comment]
Related: https://github.com/Storj/core/issues/143

**Comment by super3** [comment]
Been fixed.

**Comment by CzBaer** [comment]
This hasn't been fixed. The problem is still there with the latest version.
