### ISSUE TITLE
Storjshare CLI Errors out when running storjshare command

### ISSUE THREAD

**Issue by brad-pea** [Storj/storjshare-cli#70]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: v3.0.6
Core:   v0.6.16
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```

### Expected Behavior

Storjshare should run continuously without issue

### Actual Behavior

When running trhe storjshare command and specifying a datadir ... it will run for around 5 minutes then errors out with the below message ..

throw er; // unhandles 'error' event

Error: IO error: (path to storage)\farmer.db\059170.ldb
at error (native)

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Not sure on how to reproduce - in my instance if i run the command again it just throws the same issue...

**Comment by littleskunk** [comment]
In farmer.db folder you will find a `LOG` file. Please copy the lines with the current timestamp at the time of the crash.

**Comment by super3** [comment]
@brad-pea Missing log output from you to be able to debug this issue.
@brad-pea A major version was released two days after you made this issue, and will be deployed in the next few hours. Please verify this issue happens again with the new version, and we can reopen the ticket.

**Comment by super3** [comment]
@littleskunk This looks similar to https://github.com/Storj/storjshare-cli/issues/71
