### ISSUE TITLE
I/O Error upon start

### ISSUE THREAD

**Issue by bananenwilly** [Storj/storjshare-cli#71]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: v3.0.6
Core:   v0.6.16
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```

### Expected Behavior

Starting. 

### Actual Behavior

Crash.

### Steps to Reproduce

When I try to launch storjshare with

storjshare -d /media/storj/.storjshare/ -p mypassword

it crashes.
Error:

```
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-06-06T10:21:02.505Z"}
{"level":"info","message":"node created with nodeID 019b6399386618500fddaa082972f7af9364a8d8","timestamp":"2016-06-06T10:21:03.122Z"}
{"level":"info","message":"attemting to join network via {\"protocol\":\"0.6.16\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"78cfca0e01235db817728aec056d007672ffac63\",\"lastSeen\":1465208463080}","timestamp":"2016-06-06T10:21:03.136Z"}

events.js:141
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: /media/storj/.storjshare/farmer.db: Invalid argument
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/levelup.js:119:34
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16

```

I use a qnap nas and the cifs drive is mounted with 

//192.168.178.25/storj /media/storj cifs auto,username=user,password=password,_netdev,uid=1000,gid=1000,iocharset=utf8 0 0

My config.json looks like this:

cat config.json 
{
  "keypath": "/media/storj/.storjshare/id_ecdsa",
  "address": "mypayoutaddress",
  "storage": {
    "path": "/media/storj/.storjshare/farmer.db",
    "size": 10,
    "unit": "TB"
  },
  "network": {
    "address": "127.0.0.1",
    "port": 32525,
    "seeds": [
      "storj://api.storj.io:8443/78cfca0e01235db817728aec056d007672ffac63"
    ],
    "opcodes": [
      "0f01020202",
      "0f02020202",
      "0f03020202"
    ],
    "forward": false,
    "tunnels": 3,
    "tunnelport": 12335,
    "gateways": {
      "min": 0,
      "max": 0
    }
  },
  "telemetry": {
    "service": "https://status.storj.io",
    "enabled": true
  }
}

/media/storj/.storjshare $ ls -la
total 2
drwxr-xr-x 2 pi pi   0 Jun  6 10:19 .
drwxr-xr-x 2 pi pi   0 Jun  6 10:18 ..
-rwxr-xr-x 1 pi pi 658 Jun  6 10:19 config.json
drwxr-xr-x 2 pi pi   0 Jun  6 10:21 farmer.db
-rwxr-xr-x 1 pi pi 109 Jun  6 10:19 id_ecdsa

/media/storj/.storjshare/farmer.db $ ls -la
total 2
drwxr-xr-x 2 pi pi   0 Jun  6 10:21 .
drwxr-xr-x 2 pi pi   0 Jun  6 10:19 ..
-rwxr-xr-x 1 pi pi   0 Jun  6 10:19 000003.log
-rwxr-xr-x 1 pi pi   0 Jun  6 10:20 000004.log
-rwxr-xr-x 1 pi pi   0 Jun  6 10:21 000005.log
-rwxr-xr-x 1 pi pi  16 Jun  6 10:19 CURRENT
-rwxr-xr-x 1 pi pi   0 Jun  6 10:19 LOCK
-rwxr-xr-x 1 pi pi 223 Jun  6 10:21 LOG
-rwxr-xr-x 1 pi pi 169 Jun  6 10:20 LOG.old
-rwxr-xr-x 1 pi pi  41 Jun  6 10:19 MANIFEST-000001

**Comment by super3** [comment]
@brad-pea This looks similar to your issue. 
@bananenwilly New version https://github.com/Storj/storjshare-cli/releases. Mind retrying to see if the error exists in the new software?

**Comment by bananenwilly** [comment]
I folllowed the instructions on https://github.com/Storj/storjshare-cli
and did 
npm install -g storjshare-cli

again on two separate raspberry pis.

storjshare start --datadir /media/storj/.storjshare
 [...]  > Unlock your private key to start storj  >  ***********

{"level":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-06-11T09:35:08.797Z"}
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-06-11T09:35:08.840Z"}

events.js:141
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: /media/storj/.storjshare/farmer.db: Invalid argument
    at /home/pi/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/levelup.js:119:34
    at /home/pi/.nvm/versions/node/v4.4.4/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16

**Comment by bananenwilly** [comment]
Using the same nas via iSCSI works like a charm.

**Comment by super3** [comment]
Outdated issue. Please open a new issue if there is still problems.
