### ISSUE TITLE
Feature Request: Generate Logs

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#78]
Ability to specify log save path location in the config and for it to generate the logs.

Part of the ability is there with the Log Level then that can be expanded into full logging capabilities.

**Comment by bookchin** [comment]
Why not pipe the output to the file you want?

```
storjshare start >> logfile.txt
```

**Comment by computeronix** [comment]
Currently do :)

However working on getting it to run as a service and it is easier if it does it, itself :)

**Comment by computeronix** [comment]
And the code could be reused for the gui where you can't pipe

**Comment by bookchin** [comment]
Right now the logger is a `ReadableStream` that pumps out newline terminated JSON. By default we pipe it to `process.stdout`, so it should be trivial to pipe to a file if one is specified in the config using `fs.createWriteStream`.

I won't be able to get to it for some time, but would accept a PR in the meantime if you cannot wait.

**Comment by computeronix** [comment]
No problem no rush. Was just thinking about it and filed. In meantime will use standard out

**Comment by 1credit** [comment]
Please consider adding a max size based wrap function as well.  I have one of my eight nodes running at log level 3 and its generating about a GB of log per day.  Rather use that space for shards <smile>.

**Comment by computeronix** [comment]
When reviewing logs could you put the two logs used to help calculate concurrency as warn level logs so that way can perform actions on them while all my logging is turned down to 2

**Comment by 1credit** [comment]
Or alternatively to computeronix request,  keep internal counters and provide a query function to see them, and or post a warning once an hour or so with that specific stat if it exceeds 10% (or ideally whatever warning level the user sets)

**Comment by super3** [comment]
Use the instructions for setting up pm2 in the README. pm2 will do all that stuff for you with some config.

**Comment by 1credit** [comment]
pm2 is not a standard package on my Gentoo based systems.

**Comment by super3** [comment]
Its in the README: https://github.com/Storj/storjshare-cli#running-in-the-background

**Comment by bookchin** [comment]
@1credit once you get setup with PM2, play around with https://github.com/Unitech/pm2#log-facilities - I'm certain there are options for log rotation, etc

**Comment by 1credit** [comment]
Alas, going out of town shortly, will need to play with this when I return on Tuesday.  I did get it installed.  Currently just using log rotate, but this appears to be a superior tool.  I do recall being concerned about pm2 being able to handle 4 instances of storjshare running on the same physical machine - I didn't see much in the examples that would allow me to differentiate between the instances.
