### ISSUE TITLE
Receiving error: "Error is storage manager: ENOENT: no such file or directory"

### ISSUE THREAD

**Issue by lazerdye** [Storj/storjshare-cli#79]
Replace the values below using the output from `storjshare --version`.

```
StorjShare: 4.0.1
Core:       1.1.0
Protocol:   0.7.0
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

Note: This is an odroid arm box:
Linux cdroid 3.10.101-odroidxu4 #3 SMP PREEMPT Mon May 23 22:45:55 CEST 2016 armv7l GNU/Linux

### Expected Behavior

Expected to run without file system errors.

### Actual Behavior

Storj appears to run normally, and appears to be taking in shards. But occasionally in the log I see errors like below:

```
{"level":"error","message":"Error is storage manager: ENOENT: no such file or directory, stat '/home/storj/opt/.storjshare/farmer.db/009951.ldb'","timestamp":"2016-06-09T04:51:30.286Z"}
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run storjshare.js
2. Wait a few hours
3. See error messages.

**Comment by subwolf** [comment]
Had the same.
````
storjshare-0 {"level":"error","message":"Error is storage manager: ENOENT: no such file or directory, stat '/root/.storjshare/farmer.db/1085531.ldb'","timestamp":"2016-06-09T07:40:35.278Z"}
````

I do see it deleted in the log:
````
root@subwolf-nas:~/.storjshare/farmer.db# grep "2016/06/09-07:40:35" LOG
2016/06/09-07:40:35.007489 7f2200061700 compacted to: files[ 0 3 65 762 5772 23355 0 ]
2016/06/09-07:40:35.028241 7f2200061700 Delete type=2 #1085535
2016/06/09-07:40:35.031409 7f2200061700 Delete type=2 #1085537
2016/06/09-07:40:35.055703 7f2200061700 Delete type=2 #1085533
2016/06/09-07:40:35.057046 7f2200061700 Delete type=2 #1149869
2016/06/09-07:40:35.059462 7f2200061700 Delete type=2 #1085538
2016/06/09-07:40:35.071559 7f2200061700 Delete type=2 #1085534
2016/06/09-07:40:35.076217 7f2200061700 Delete type=2 #1085536
2016/06/09-07:40:35.078796 7f2200061700 Delete type=2 #1085531 <---
````

**Comment by subwolf** [comment]
Could it be a reaper thread is deleting a file, meanwhile another thread expects to find it? This is where some kind of lock might come in, or double-check existence before acting.

**Comment by airatru** [comment]
Got it with this version:
StorjShare: 4.0.2
Core:       1.2.3
Protocol:   0.7.0

{"level":"error","message":"Error is storage manager: ENOENT: no such file or directory, stat '/media/pi/storj/.storjshare/farmer.db/201173.ldb'","timestamp":"2016-06-16T16:15:03.972Z"}
