### ISSUE TITLE
Unable to use new auto discovery seed feature

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#82]
### Package Versions

```
StorjShare: 4.0.2
Core:       1.2.1
Protocol:   0.7.0
```
### Expected Behavior

Auto find and use a seed

Config looks like this (generated from setup with blank for auto discovery)
    "seeds": [],

### Actual Behavior

error occurs and nothing else happens

{"level":"info","message":"resolving seeds from [object Object]","timestamp":"2016-06-10T19:10:12.536Z"}

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run the setup
2. Use the blank for seed so it auto discovers
3. complete setup
4. run newly setup node

See it fail

**Comment by bookchin** [comment]
Bridge was offline, sorry
