### ISSUE TITLE
When the node cannot find a seed; app crashes

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#83]
When the node cannot find the seed the app eventually just crashes with the error

events.js:141
      throw er; // Unhandled 'error' event
      ^
 OpenError: IO error: E:\.storjshare\farmer.db/000001.dbtmp: The file exists.

    at ...\npm\node_modules\storjshare-cli\node_modul
es\storj\node_modules\levelup\lib\levelup.js:119:34
    at ....\npm\node_modules\storjshare-cli\node_modul
es\storj\node_modules\leveldown\node_modules\abstract-leveldown\abstract-leveldo
wn.js:39:16

**Comment by kusabnis** [comment]
Can you provide the complete stack trace?

**Comment by bookchin** [comment]
This doesn't appear to be related to any networking. It's coming out of the storage adapter. There a few other issues reported that are similar to this, so I'm going to close it as a duplicate.
