### ISSUE TITLE
Drive Unavailable while running

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#85]
If the drive becomes unavailable while running the application crashes

Then

When the drive is restored and the application is re-run it will no longer work until the database is recreated

Giving this error: 

events.js:141
      throw er; // Unhandled 'error' event
      ^
 OpenError: IO error: [blank]\storjshare\farmer.db/MANIFEST-009297: A device attached
 to the system is not functioning.

    at [blank]\\npm\node_modules\storjshare-cli\node_modules\storj\node_modules\levelup\lib\levelup.js:119:34
    at [blank]\\npm\node_modules\storjshare-cli\node_modules\storj\node_modules\leveldown\node_modules\abstract-leveldown\abstract-leveldown.js:39:16

**Comment by littleskunk** [comment]
As soon as tunnel connection are stable I will try to reproduce it with an usb stick.

**Comment by littleskunk** [comment]
Do you have some more informations for me? OS? The storage part of your config file? That will help me to reproduce the bug.

**Comment by computeronix** [comment]
OS: Windows Server 2012 R2

Storage is located on an E drive    E:\storjshare

The E drive is networked based drive (NAS type situation).  If you knock this drive offline the above issue occurs and appears to potentially corrupt all of farms.db  (see if you can replicate that; using a USB stick in theory work)

**Comment by computeronix** [comment]
We can close this up as it appears fixed in the latest version
