### ISSUE TITLE
npm update did not work for core version

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#86]
### Package Versions

Core version 1.2.1 does not auto upgrade to 1.2.2 when performing npm upgrade -g storjshare-cli (did this on windows)

### Expected Behavior

When you perform npm update -g storjshare-cli it would analyze storjshare-cli / core / protocol and update those packages that are out of date

### Actual Behavior

Nothing happens when attempting to run the update command even though 1.2.2 is out

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Install storjshare-cli 1.2.1 core /////  perform update command

Workaround:

Run npm install -g storjshare-cli and this installs the latest 1.2.2 core

**Comment by bookchin** [comment]
Please see [the documentation on `npm update`](https://docs.npmjs.com/cli/update) and open an issue at the NPM repository if the information there is incorrect.
