### ISSUE TITLE
Received Visual Studio error from app

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#90]
### Package Versions

```
StorjShare: 4.0.3
Core:       1.2.6
Protocol:   0.7.0

Node: v4.4.5
```

Run the application for a while and eventually this error popped up

![screen shot 2016-06-17 at 8 49 59 am](https://cloud.githubusercontent.com/assets/19168174/16151049/cab83112-3468-11e6-932a-2397dddd24ff.png)

**Comment by bookchin** [comment]
I'd open this at https://github.com/Level/leveldown - closing it here.
