### ISSUE TITLE
storjshare ignore free diskspace an write until it is full if limit > free space

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/storjshare-cli#92]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
└─┬ storjshare-cli@4.0.3
  └── storj@1.2.6
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

I expect that storjshare stops farming if free diskspace is < 10GB, to keep system responsive.

### Actual Behavior

Disk limit work, but if more space is assign then exist, storjshare fill the disk up to last bit, and crash. In this case no shard will be reachable. 

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Set size limit more than disk space
2. Wait until disk is full

**Comment by 1credit** [comment]
Under SG2's cli there was a parameter that would force the system to try an maintain a minimum amount of free space.  That likely defaulted to 10g, but could be set to any value, protecting the integrity of servers that primary serve up disk space.   Please provide that functionality again, it would significantly simplify my installation since I now break up my free space into 1TB chunks, just so that I could reclaim one chunk should I need the space, without invalidating the remaining chunks.

**Comment by utdrmac** [comment]
I just want to comment on a recent discovery. In Ubuntu, using GParted, all calculations are based on 'Mebibytes'. Thus, if you create a partition 20GB (20480MB) in size, you actually created a partition 21474.836 MB in size. `df` reports this as 20031 1M-blocks and "20GB"

![gparted20gb](https://cloud.githubusercontent.com/assets/4413670/17300200/f86bc704-57d6-11e6-9066-5a0651d055a2.png)

**Comment by utdrmac** [comment]
```
root@drmac-ubuntu:~# df --si /dev/sdb2
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb2        20G   47M   19G   1% /opt/storjB20gb
 
root@drmac-ubuntu:~# df -h /dev/sdb2
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb2        19G   44M   18G   1% /opt/storjB20gb
```

**Comment by BlackDuck888** [comment]
@utdrmac https://github.com/Storj/core/blob/master/lib/utils.js#L155

**Comment by 1credit** [comment]
@BlackDuck888 As it should be!

**Comment by bookchin** [comment]
Yes, we use the correct unit :) However, this issue pops up a lot, so we might need to think about how to handle this appropriately. I don't want to change the unit (there are likely a number of negative side effects to doing so).

**Comment by bookchin** [comment]
Also: https://github.com/Storj/storjshare-cli/issues/131#issuecomment-234678404

**Comment by 1credit** [comment]
I really hate to suggest this, and blame all the confusion on Western Digital when their marketing people started calling a MB 1-million bytes when they released their 30MB 5 1/2 inch disk drive, but...

Maybe output both numbers (e.g:  8GB, 8.2GiB - or whatever today's language is)???

**Comment by davidak** [comment]
@1credit most people won't understand what that means and when they do, it feels very strange. not a good idea in term of usability.

**Comment by 1credit** [comment]
Perhaps a "units" option for display output?   Low priority in my mind.

**Comment by utdrmac** [comment]
I think this needs to be re-opened because issue remains: https://github.com/Storj/storjshare-gui/issues/372
