### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by tankmann** [Storj/storjshare-cli#95]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
StorjShare: 4.0.3
Core:       1.2.7
Protocol:   0.7.0
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

CLI should just run fine without any big increase in memory usage or at least not force the system to swap even if CPU load is very high

### Actual Behavior

Memory increases with the amount of time storjshare is running. 

```
- Running Mac OSX but CLI through SSH with pm2
- CPU: Intel(R) Core(TM)2 Duo CPU     P8700  @ 2.53GHz
- After restart (machine and CLI): MemRegions: 14582 total, 1793M resident, 25M private, 87M shared. PhysMem: 2545M used (1015M wired), 1807M unused.
- 4 GB RAM
```
## **Screenshots:**
**CPU Usage (24h/12h):**
![cpu_usage_24h](https://cloud.githubusercontent.com/assets/19350453/16209756/bf208796-3738-11e6-9c45-3a15d59a7b49.png)
![cpu_usage_12h](https://cloud.githubusercontent.com/assets/19350453/16209760/c326817e-3738-11e6-900f-bca9ecdeb2bb.png)
**Memory (24h/12h):**
![memory_24h](https://cloud.githubusercontent.com/assets/19350453/16209772/d4fb18f6-3738-11e6-932f-b206a78fe5b3.png)
![memory_12h](https://cloud.githubusercontent.com/assets/19350453/16209774/d715b9ca-3738-11e6-8e2e-a75c3b85b79e.png)
**Memory Pressure (24h)**
![memory_pressure_24h](https://cloud.githubusercontent.com/assets/19350453/16209787/e40b905a-3738-11e6-9b51-270d8ae34fa9.png)
**Traffic (24h)**
![traffic_24h](https://cloud.githubusercontent.com/assets/19350453/16209798/f0171ef0-3738-11e6-9cb5-155bcd0ca1c6.png)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Let it run for more than 24 hours and make sure you get shards. That's it.

**Comment by bookchin** [comment]
Thanks for the detailed report! Will investigate.
