### ISSUE TITLE
2 instances not work.

### ISSUE THREAD

**Issue by luishmendes** [Storj/storjshare-cli#98]
StorjShare: 4.0.4
Core:       1.3.1
Protocol:   0.7.0

C:\Users\Luis>node --version
v4.4.5

CLI with 1 instance works 100% With 2 instances not work the 2 instance.

C:\Users\Luis>storjshare start --datadir e:\cli
 [...]  > Unlock your private key to start storj  >  *********

{"level":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-06-24T18:19:40.212Z"}
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-06-24T18:19:40.220Z"}
{"level":"warn","message":"could not connect to NAT device via UPnP","timestamp":"2016-06-24T18:19:41.259Z"}
{"level":"error","message":"failed to map port for tunserver: connect ECONNREFUSED 192.168.1.142:3159","timestamp":"2016-06-24T18:19:41.260Z"}
{"level":"warn","message":"could not obtain public IP address","timestamp":"2016-06-24T18:19:41.522Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at Transport.HTTPTransport._open (C:\Users\Luis\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\node_modules\kad\lib\transports\http.js:83:16)
    at C:\Users\Luis\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\lib\network\transport.js:72:41
    at C:\Users\Luis\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\lib\network\transport.js:100:16
    at C:\Users\Luis\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\node_modules\nat-upnp\lib\nat-upnp\client.js:158:23
    at C:\Users\Luis\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\node_modules\nat-upnp\lib\nat-upnp\device.js:117:21

C:\Users\Luis>

Config 1 instance:

{
  "keypath": "d:\\cli\\id_ecdsa",
  "address": "167Xg7hFofTfHLdxiBQGGjduk9bSyg1CwD",
  "storage": {
    "path": "d:/cli",
    "size": 3300,
    "unit": "GB"
  },
  "network": {
    "address": "127.0.0.1",
    "port": 4000,
    "seeds": [],
    "opcodes": [
      "0f01020202",
      "0f02020202",
      "0f03020202"
    ],
    "forward": true,
    "tunnels": 3,
    "tunnelport": 0,
    "gateways": {
      "min": 0,
      "max": 0
    }
  },
  "telemetry": {
    "service": "https://status.storj.io",
    "enabled": true
  },
  "loglevel": 3
}

Config 2 instance   (  not Work )

{
  "keypath": "e:\\cli\\id_ecdsa",
  "address": "124NGM7RWiJVLw8vhauq33X5fafDMcQetN",
  "storage": {
    "path": "e:\\cli",
    "size": 4000,
    "unit": "GB"
  },
  "network": {
    "address": "127.0.0.1",
    "port": 4000,
    "seeds": [],
    "opcodes": [
      "0f01020202",
      "0f02020202",
      "0f03020202"
    ],
    "forward": true,
    "tunnels": 3,
    "tunnelport": 0,
    "gateways": {
      "min": 0,
      "max": 0
    }
  },
  "telemetry": {
    "service": "https://status.storj.io",
    "enabled": true
  },
  "loglevel": 3
}

**Comment by bookchin** [comment]
You must specify a different data directory. If you run multiple processes with the same config, it will try to listen on the same port (doesn't work) and use the same LevelDB database (also doesn't work).

Use a different config if you wish to run multiple nodes. You can setup a new datadir with: 

```
storjshare --datadir /path/to/datadir setup
```

**Comment by bookchin** [comment]
After looking again at this, it looks like you *are* using 2 datadirs, but both are configured to listen on the same port. Just change your other config to listen in a different port.

**Comment by luishmendes** [comment]
Thanks, problem is solved. It already working on all Hard Disks
